"""Gazetteer determinista: países, bloques, instituciones y actores públicos.

Sirve para (1) enlazar documentos a países y entidades sin LLM, (2) exigir coincidencia de entidad en el
clustering, (3) medir amplitud geográfica en la materialidad y (4) poner los eventos en el mapa.
Los alias están en es/en/fr/de/it/pt. Nombres de personas: figuras públicas en su dimensión pública; el cargo se
guarda como nota orientativa (puede quedar desfasado) y nunca se afirma en la UI sin fuente.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from functools import lru_cache

from .embed import normalize_text


@dataclass(frozen=True)
class Country:
    iso2: str
    name_es: str
    name_en: str
    lat: float
    lon: float
    bloc: str
    aliases: tuple[str, ...] = field(default_factory=tuple)


# iso2, name_es, name_en, lat, lon, region_bloc, aliases (demonyms/adjectives/capital where unambiguous)
_C: list[tuple] = [
    (
        "ES",
        "España",
        "Spain",
        40.4,
        -3.7,
        "es",
        ("español", "española", "españoles", "spanish", "espagne", "spanien", "spagna", "madrid", "moncloa"),
    ),
    (
        "US",
        "Estados Unidos",
        "United States",
        38.9,
        -77.0,
        "anglo",
        (
            "ee. uu.",
            "eeuu",
            "ee.uu.",
            "estadounidense",
            "u.s.",
            "usa",
            "american",
            "americans",
            "washington",
            "casa blanca",
            "white house",
            "états-unis",
            "etats-unis",
            "américain",
            "vereinigte staaten",
            "stati uniti",
            "pentagon",
            "pentágono",
            "congreso de ee",
            "u.s. congress",
        ),
    ),
    (
        "CN",
        "China",
        "China",
        39.9,
        116.4,
        "china",
        (
            "chino",
            "china",
            "chinese",
            "beijing",
            "pekín",
            "pekin",
            "chine",
            "chinois",
            "cina",
            "cinese",
            "xi jinping",
            "pcch",
            "partido comunista chino",
        ),
    ),
    (
        "RU",
        "Rusia",
        "Russia",
        55.8,
        37.6,
        "russia",
        (
            "ruso",
            "rusa",
            "rusos",
            "russian",
            "moscú",
            "moscow",
            "moscou",
            "russie",
            "russe",
            "russland",
            "kremlin",
            "kremlín",
        ),
    ),
    (
        "UA",
        "Ucrania",
        "Ukraine",
        50.4,
        30.5,
        "russia",
        (
            "ucraniano",
            "ucraniana",
            "ukrainian",
            "kiev",
            "kyiv",
            "zelenski",
            "zelensky",
            "zelenskyy",
            "ucraina",
            "ukrainien",
        ),
    ),
    (
        "TR",
        "Turquía",
        "Turkey",
        39.9,
        32.9,
        "turkey",
        (
            "turco",
            "turca",
            "turkish",
            "türkiye",
            "ankara",
            "erdogan",
            "erdoğan",
            "turquie",
            "türkei",
            "turchia",
        ),
    ),
    (
        "FR",
        "Francia",
        "France",
        48.9,
        2.4,
        "eu",
        (
            "francés",
            "francesa",
            "franceses",
            "french",
            "parís",
            "paris",
            "elíseo",
            "élysée",
            "macron",
            "frankreich",
            "französisch",
            "francia",
            "française",
        ),
    ),
    (
        "DE",
        "Alemania",
        "Germany",
        52.5,
        13.4,
        "eu",
        (
            "alemán",
            "alemana",
            "alemanes",
            "german",
            "germany",
            "berlín",
            "berlin",
            "bundestag",
            "deutschland",
            "deutsche",
            "allemagne",
            "allemand",
            "germania",
            "merz",
            "bundesbank",
        ),
    ),
    (
        "GB",
        "Reino Unido",
        "United Kingdom",
        51.5,
        -0.1,
        "anglo",
        (
            "británico",
            "británica",
            "british",
            "uk",
            "u.k.",
            "britain",
            "gran bretaña",
            "london",
            "londres",
            "downing street",
            "westminster",
            "royaume-uni",
            "großbritannien",
            "regno unito",
            "starmer",
            "inglaterra",
            "england",
            "escocia",
            "scotland",
        ),
    ),
    (
        "IT",
        "Italia",
        "Italy",
        41.9,
        12.5,
        "eu",
        ("italiano", "italiana", "italian", "roma", "rome", "meloni", "italie", "italien", "palazzo chigi"),
    ),
    (
        "IL",
        "Israel",
        "Israel",
        31.8,
        35.2,
        "arab",
        (
            "israelí",
            "israelíes",
            "israeli",
            "netanyahu",
            "tel aviv",
            "jerusalén",
            "jerusalem",
            "idf",
            "fdi",
            "knesset",
            "israël",
            "israele",
        ),
    ),
    (
        "PS",
        "Palestina",
        "Palestine",
        31.9,
        35.2,
        "arab",
        (
            "palestino",
            "palestina",
            "palestinian",
            "gaza",
            "cisjordania",
            "west bank",
            "hamás",
            "hamas",
            "ramala",
            "ramallah",
            "palestinien",
            "palästin",
        ),
    ),
    (
        "IR",
        "Irán",
        "Iran",
        35.7,
        51.4,
        "arab",
        (
            "iraní",
            "iraníes",
            "iranian",
            "teherán",
            "tehran",
            "jamenei",
            "khamenei",
            "guardianes de la revolución",
            "irgc",
        ),
    ),
    (
        "SA",
        "Arabia Saudí",
        "Saudi Arabia",
        24.7,
        46.7,
        "arab",
        (
            "saudí",
            "saudíes",
            "saudi",
            "riad",
            "riyadh",
            "bin salmán",
            "bin salman",
            "mbs",
            "arabie saoudite",
            "saudi-arabien",
            "arabia saudita",
        ),
    ),
    (
        "IN",
        "India",
        "India",
        28.6,
        77.2,
        "india",
        ("indio", "india", "indian", "nueva delhi", "new delhi", "modi", "inde", "indien", "bharat"),
    ),
    (
        "BR",
        "Brasil",
        "Brazil",
        -15.8,
        -47.9,
        "latam",
        (
            "brasileño",
            "brasileña",
            "brazilian",
            "brasilia",
            "brasília",
            "lula",
            "bolsonaro",
            "brésil",
            "brasilien",
            "brasile",
            "brazil",
        ),
    ),
    (
        "MX",
        "México",
        "Mexico",
        19.4,
        -99.1,
        "latam",
        ("mexicano", "mexicana", "mexican", "sheinbaum", "mexique", "mexiko", "messico", "ciudad de méxico"),
    ),
    (
        "AR",
        "Argentina",
        "Argentina",
        -34.6,
        -58.4,
        "latam",
        ("argentino", "argentina", "argentine", "argentinian", "buenos aires", "milei", "argentinien"),
    ),
    (
        "MC",
        "Mónaco",
        "Monaco",
        43.7,
        7.4,
        "eu",
        ("monegasco", "monegasque", "monaco", "montecarlo", "monte-carlo"),
    ),
    ("AD", "Andorra", "Andorra", 42.5, 1.5, "eu", ("andorrano", "andorran", "andorre")),
    (
        "PT",
        "Portugal",
        "Portugal",
        38.7,
        -9.1,
        "eu",
        ("portugués", "portuguesa", "portuguese", "lisboa", "lisbon", "lisbonne"),
    ),
    (
        "NL",
        "Países Bajos",
        "Netherlands",
        52.4,
        4.9,
        "eu",
        (
            "neerlandés",
            "neerlandesa",
            "holanda",
            "holandés",
            "dutch",
            "netherlands",
            "ámsterdam",
            "amsterdam",
            "la haya",
            "the hague",
            "pays-bas",
            "niederlande",
        ),
    ),
    (
        "BE",
        "Bélgica",
        "Belgium",
        50.8,
        4.4,
        "eu",
        ("belga", "belgian", "bruselas", "brussels", "bruxelles", "brüssel", "belgique", "belgien", "belgio"),
    ),
    (
        "PL",
        "Polonia",
        "Poland",
        52.2,
        21.0,
        "eu",
        ("polaco", "polaca", "polish", "varsovia", "warsaw", "pologne", "polen", "polonia", "tusk"),
    ),
    (
        "SE",
        "Suecia",
        "Sweden",
        59.3,
        18.1,
        "eu",
        ("sueco", "sueca", "swedish", "estocolmo", "stockholm", "suède", "schweden", "svezia"),
    ),
    (
        "GR",
        "Grecia",
        "Greece",
        38.0,
        23.7,
        "eu",
        ("griego", "griega", "greek", "atenas", "athens", "grèce", "griechenland", "mitsotakis"),
    ),
    (
        "CH",
        "Suiza",
        "Switzerland",
        46.9,
        7.4,
        "eu",
        (
            "suizo",
            "suiza",
            "swiss",
            "berna",
            "ginebra",
            "geneva",
            "zúrich",
            "zurich",
            "suisse",
            "schweiz",
            "svizzera",
        ),
    ),
    (
        "AT",
        "Austria",
        "Austria",
        48.2,
        16.4,
        "eu",
        ("austriaco", "austríaco", "austrian", "viena", "vienna", "wien", "autriche", "österreich"),
    ),
    (
        "IE",
        "Irlanda",
        "Ireland",
        53.3,
        -6.3,
        "eu",
        ("irlandés", "irlandesa", "irish", "dublín", "dublin", "irlande", "irland"),
    ),
    (
        "CA",
        "Canadá",
        "Canada",
        45.4,
        -75.7,
        "anglo",
        ("canadiense", "canadian", "ottawa", "carney", "kanada"),
    ),
    (
        "JP",
        "Japón",
        "Japan",
        35.7,
        139.7,
        "japan_korea",
        ("japonés", "japonesa", "japanese", "tokio", "tokyo", "japon", "japan", "giappone", "nikkei", "boj"),
    ),
    (
        "KR",
        "Corea del Sur",
        "South Korea",
        37.6,
        127.0,
        "japan_korea",
        (
            "surcoreano",
            "surcoreana",
            "south korean",
            "seúl",
            "seoul",
            "corée du sud",
            "südkorea",
            "corea del sud",
            "korea",
        ),
    ),
    (
        "KP",
        "Corea del Norte",
        "North Korea",
        39.0,
        125.8,
        "japan_korea",
        (
            "norcoreano",
            "north korean",
            "pyongyang",
            "kim jong-un",
            "kim jong un",
            "corée du nord",
            "nordkorea",
        ),
    ),
    (
        "TW",
        "Taiwán",
        "Taiwan",
        25.0,
        121.6,
        "china",
        ("taiwanés", "taiwanesa", "taiwanese", "taipéi", "taipei", "taïwan", "formosa"),
    ),
    (
        "AU",
        "Australia",
        "Australia",
        -35.3,
        149.1,
        "oceania",
        (
            "australiano",
            "australiana",
            "australian",
            "canberra",
            "sídney",
            "sydney",
            "australie",
            "australien",
            "albanese",
        ),
    ),
    (
        "NZ",
        "Nueva Zelanda",
        "New Zealand",
        -41.3,
        174.8,
        "oceania",
        ("neozelandés", "new zealand", "wellington", "nouvelle-zélande", "neuseeland"),
    ),
    (
        "ID",
        "Indonesia",
        "Indonesia",
        -6.2,
        106.8,
        "other_asia",
        ("indonesio", "indonesia", "indonesian", "yakarta", "jakarta", "prabowo", "indonésie", "indonesien"),
    ),
    ("PK", "Pakistán", "Pakistan", 33.7, 73.0, "india", ("pakistaní", "pakistani", "islamabad", "pakistan")),
    (
        "BD",
        "Bangladés",
        "Bangladesh",
        23.8,
        90.4,
        "india",
        ("bangladesí", "bangladeshi", "daca", "dhaka", "bangladesh"),
    ),
    (
        "AF",
        "Afganistán",
        "Afghanistan",
        34.5,
        69.2,
        "other_asia",
        ("afgano", "afgana", "afghan", "kabul", "talibán", "taliban", "talibanes", "afghanistan"),
    ),
    (
        "EG",
        "Egipto",
        "Egypt",
        30.0,
        31.2,
        "arab",
        (
            "egipcio",
            "egipcia",
            "egyptian",
            "el cairo",
            "cairo",
            "sisi",
            "égypte",
            "ägypten",
            "egitto",
            "egypt",
        ),
    ),
    (
        "AE",
        "Emiratos Árabes Unidos",
        "United Arab Emirates",
        24.5,
        54.4,
        "arab",
        (
            "emiratí",
            "emirati",
            "emiratos",
            "uae",
            "abu dabi",
            "abu dhabi",
            "dubái",
            "dubai",
            "émirats",
            "emirate",
        ),
    ),
    ("QA", "Catar", "Qatar", 25.3, 51.5, "arab", ("catarí", "qatarí", "qatari", "doha", "qatar", "katar")),
    (
        "MA",
        "Marruecos",
        "Morocco",
        34.0,
        -6.8,
        "arab",
        (
            "marroquí",
            "marroquíes",
            "moroccan",
            "rabat",
            "morocco",
            "maroc",
            "marokko",
            "marocco",
            "mohamed vi",
            "ceuta",
            "melilla",
            "sáhara occidental",
            "western sahara",
        ),
    ),
    (
        "DZ",
        "Argelia",
        "Algeria",
        36.8,
        3.1,
        "arab",
        (
            "argelino",
            "argelina",
            "algerian",
            "argel",
            "algiers",
            "algeria",
            "algérie",
            "algerien",
            "tebboune",
        ),
    ),
    (
        "TN",
        "Túnez",
        "Tunisia",
        36.8,
        10.2,
        "arab",
        ("tunecino", "tunecina", "tunisian", "tunisia", "tunisie", "tunesien"),
    ),
    (
        "LY",
        "Libia",
        "Libya",
        32.9,
        13.2,
        "arab",
        ("libio", "libia", "libyan", "trípoli", "tripoli", "libya", "libye", "libyen"),
    ),
    (
        "SD",
        "Sudán",
        "Sudan",
        15.6,
        32.5,
        "africa",
        (
            "sudanés",
            "sudanesa",
            "sudanese",
            "jartum",
            "khartoum",
            "sudan",
            "soudan",
            "darfur",
            "rsf",
            "fuerzas de apoyo rápido",
        ),
    ),
    (
        "NG",
        "Nigeria",
        "Nigeria",
        9.1,
        7.5,
        "africa",
        ("nigeriano", "nigeriana", "nigerian", "abuya", "abuja", "lagos", "nigéria", "tinubu"),
    ),
    (
        "ZA",
        "Sudáfrica",
        "South Africa",
        -25.7,
        28.2,
        "africa",
        (
            "sudafricano",
            "sudafricana",
            "south african",
            "pretoria",
            "johannesburgo",
            "johannesburg",
            "ramaphosa",
            "afrique du sud",
            "südafrika",
            "south africa",
        ),
    ),
    (
        "ET",
        "Etiopía",
        "Ethiopia",
        9.0,
        38.7,
        "africa",
        (
            "etíope",
            "ethiopian",
            "adís abeba",
            "addis ababa",
            "addis abeba",
            "abiy",
            "tigray",
            "ethiopia",
            "éthiopie",
            "äthiopien",
        ),
    ),
    (
        "KE",
        "Kenia",
        "Kenya",
        -1.3,
        36.8,
        "africa",
        ("keniano", "keniata", "kenyan", "nairobi", "kenya", "ruto"),
    ),
    (
        "CD",
        "República Democrática del Congo",
        "DR Congo",
        -4.3,
        15.3,
        "africa",
        ("congoleño", "congolese", "kinshasa", "rdc", "drc", "goma", "m23", "congo"),
    ),
    ("ML", "Malí", "Mali", 12.6, -8.0, "africa", ("maliense", "malian", "bamako", "mali")),
    ("NE", "Níger", "Niger", 13.5, 2.1, "africa", ("nigerino", "nigerien", "niamey", "niger")),
    (
        "BF",
        "Burkina Faso",
        "Burkina Faso",
        12.4,
        -1.5,
        "africa",
        ("burkinés", "burkinabé", "uagadugú", "ouagadougou", "burkina"),
    ),
    ("SN", "Senegal", "Senegal", 14.7, -17.4, "africa", ("senegalés", "senegalese", "dakar", "sénégal")),
    ("GH", "Ghana", "Ghana", 5.6, -0.2, "africa", ("ghanés", "ghanaian", "acra", "accra")),
    (
        "SO",
        "Somalia",
        "Somalia",
        2.0,
        45.3,
        "africa",
        ("somalí", "somali", "mogadiscio", "mogadishu", "al shabab", "al-shabaab", "somalie"),
    ),
    ("MZ", "Mozambique", "Mozambique", -25.9, 32.6, "africa", ("mozambiqueño", "mozambican", "maputo")),
    ("AO", "Angola", "Angola", -8.8, 13.2, "africa", ("angoleño", "angolan", "luanda")),
    (
        "CO",
        "Colombia",
        "Colombia",
        4.7,
        -74.1,
        "latam",
        ("colombiano", "colombiana", "colombian", "bogotá", "bogota", "petro", "colombie", "kolumbien"),
    ),
    (
        "CL",
        "Chile",
        "Chile",
        -33.4,
        -70.7,
        "latam",
        ("chileno", "chilena", "chilean", "santiago de chile", "kast", "chili"),
    ),
    (
        "PE",
        "Perú",
        "Peru",
        -12.0,
        -77.0,
        "latam",
        ("peruano", "peruana", "peruvian", "lima", "peru", "pérou"),
    ),
    (
        "VE",
        "Venezuela",
        "Venezuela",
        10.5,
        -66.9,
        "latam",
        ("venezolano", "venezolana", "venezuelan", "caracas", "maduro", "chavismo", "machado"),
    ),
    (
        "EC",
        "Ecuador",
        "Ecuador",
        -0.2,
        -78.5,
        "latam",
        ("ecuatoriano", "ecuatoriana", "ecuadorian", "quito", "noboa", "guayaquil", "équateur"),
    ),
    (
        "BO",
        "Bolivia",
        "Bolivia",
        -16.5,
        -68.1,
        "latam",
        ("boliviano", "boliviana", "bolivian", "la paz", "bolivie"),
    ),
    ("UY", "Uruguay", "Uruguay", -34.9, -56.2, "latam", ("uruguayo", "uruguaya", "uruguayan", "montevideo")),
    ("PY", "Paraguay", "Paraguay", -25.3, -57.6, "latam", ("paraguayo", "paraguaya", "asunción", "asuncion")),
    (
        "CU",
        "Cuba",
        "Cuba",
        23.1,
        -82.4,
        "latam",
        ("cubano", "cubana", "cuban", "la habana", "havana", "havane"),
    ),
    (
        "HT",
        "Haití",
        "Haiti",
        18.5,
        -72.3,
        "latam",
        ("haitiano", "haitiana", "haitian", "puerto príncipe", "port-au-prince", "haiti", "haïti"),
    ),
    (
        "PA",
        "Panamá",
        "Panama",
        9.0,
        -79.5,
        "latam",
        ("panameño", "panameña", "panamanian", "canal de panamá", "panama canal", "panama"),
    ),
    ("GT", "Guatemala", "Guatemala", 14.6, -90.5, "latam", ("guatemalteco", "guatemalteca", "guatemalan")),
    (
        "HN",
        "Honduras",
        "Honduras",
        14.1,
        -87.2,
        "latam",
        ("hondureño", "hondureña", "honduran", "tegucigalpa"),
    ),
    (
        "SV",
        "El Salvador",
        "El Salvador",
        13.7,
        -89.2,
        "latam",
        ("salvadoreño", "salvadoreña", "salvadoran", "bukele", "san salvador"),
    ),
    (
        "NI",
        "Nicaragua",
        "Nicaragua",
        12.1,
        -86.3,
        "latam",
        ("nicaragüense", "nicaraguan", "managua", "ortega"),
    ),
    (
        "DO",
        "República Dominicana",
        "Dominican Republic",
        18.5,
        -69.9,
        "latam",
        ("dominicano", "dominicana", "dominican", "santo domingo"),
    ),
    (
        "SY",
        "Siria",
        "Syria",
        33.5,
        36.3,
        "arab",
        (
            "sirio",
            "siria",
            "syrian",
            "damasco",
            "damascus",
            "al-sharaa",
            "al sharaa",
            "syrie",
            "syrien",
            "syria",
        ),
    ),
    (
        "LB",
        "Líbano",
        "Lebanon",
        33.9,
        35.5,
        "arab",
        (
            "libanés",
            "libanesa",
            "lebanese",
            "beirut",
            "hezbolá",
            "hezbollah",
            "hizbulá",
            "liban",
            "libanon",
            "lebanon",
        ),
    ),
    (
        "IQ",
        "Irak",
        "Iraq",
        33.3,
        44.4,
        "arab",
        ("iraquí", "iraquíes", "iraqi", "bagdad", "baghdad", "iraq", "irak", "kurdistán", "kurdistan"),
    ),
    (
        "JO",
        "Jordania",
        "Jordan",
        31.9,
        35.9,
        "arab",
        ("jordano", "jordana", "jordanian", "amán", "amman", "jordanie", "jordanien", "jordan"),
    ),
    (
        "YE",
        "Yemen",
        "Yemen",
        15.4,
        44.2,
        "arab",
        (
            "yemení",
            "yemeni",
            "saná",
            "sanaa",
            "hutíes",
            "houthis",
            "huthi",
            "houthi",
            "adén",
            "aden",
            "yémen",
            "jemen",
        ),
    ),
    ("KW", "Kuwait", "Kuwait", 29.4, 48.0, "arab", ("kuwaití", "kuwaiti", "koweït")),
    ("OM", "Omán", "Oman", 23.6, 58.5, "arab", ("omaní", "omani", "mascate", "muscat", "oman")),
    ("BH", "Baréin", "Bahrain", 26.2, 50.6, "arab", ("bareiní", "bahraini", "manama", "bahréin", "bahrain")),
    (
        "AZ",
        "Azerbaiyán",
        "Azerbaijan",
        40.4,
        49.9,
        "russia",
        (
            "azerbaiyano",
            "azeri",
            "azerbaijani",
            "bakú",
            "baku",
            "aliyev",
            "azerbaïdjan",
            "aserbaidschan",
            "azerbaijan",
        ),
    ),
    (
        "AM",
        "Armenia",
        "Armenia",
        40.2,
        44.5,
        "russia",
        (
            "armenio",
            "armenia",
            "armenian",
            "ereván",
            "yerevan",
            "pashinián",
            "pashinyan",
            "arménie",
            "armenien",
        ),
    ),
    (
        "GE",
        "Georgia",
        "Georgia",
        41.7,
        44.8,
        "russia",
        ("georgiano", "georgiana", "georgian", "tiflis", "tbilisi", "géorgie", "georgien"),
    ),
    (
        "KZ",
        "Kazajistán",
        "Kazakhstan",
        51.2,
        71.4,
        "russia",
        ("kazajo", "kazaja", "kazakh", "astaná", "astana", "almaty", "kazakhstan", "kasachstan"),
    ),
    (
        "UZ",
        "Uzbekistán",
        "Uzbekistan",
        41.3,
        69.2,
        "russia",
        ("uzbeko", "uzbek", "taskent", "tashkent", "uzbekistan"),
    ),
    (
        "BY",
        "Bielorrusia",
        "Belarus",
        53.9,
        27.6,
        "russia",
        ("bielorruso", "bielorrusa", "belarusian", "minsk", "lukashenko", "biélorussie", "belarus"),
    ),
    (
        "MD",
        "Moldavia",
        "Moldova",
        47.0,
        28.9,
        "russia",
        (
            "moldavo",
            "moldava",
            "moldovan",
            "chisináu",
            "chisinau",
            "sandu",
            "moldavie",
            "moldau",
            "moldova",
            "transnistria",
        ),
    ),
    (
        "RS",
        "Serbia",
        "Serbia",
        44.8,
        20.5,
        "eu",
        ("serbio", "serbia", "serbian", "belgrado", "belgrade", "vučić", "vucic", "serbie", "serbien"),
    ),
    ("XK", "Kosovo", "Kosovo", 42.7, 21.2, "eu", ("kosovar", "pristina", "prístina")),
    (
        "BA",
        "Bosnia y Herzegovina",
        "Bosnia and Herzegovina",
        43.9,
        18.4,
        "eu",
        ("bosnio", "bosnia", "bosnian", "sarajevo", "república srpska", "dodik", "bosnie", "bosnien"),
    ),
    (
        "HU",
        "Hungría",
        "Hungary",
        47.5,
        19.0,
        "eu",
        (
            "húngaro",
            "húngara",
            "hungarian",
            "budapest",
            "orbán",
            "orban",
            "hongrie",
            "ungarn",
            "ungheria",
            "hungary",
        ),
    ),
    (
        "RO",
        "Rumanía",
        "Romania",
        44.4,
        26.1,
        "eu",
        ("rumano", "rumana", "romanian", "bucarest", "bucharest", "roumanie", "rumänien", "romania"),
    ),
    (
        "BG",
        "Bulgaria",
        "Bulgaria",
        42.7,
        23.3,
        "eu",
        ("búlgaro", "búlgara", "bulgarian", "sofía", "sofia", "bulgarie", "bulgarien"),
    ),
    (
        "CZ",
        "Chequia",
        "Czechia",
        50.1,
        14.4,
        "eu",
        (
            "checo",
            "checa",
            "czech",
            "praga",
            "prague",
            "república checa",
            "czech republic",
            "tchéquie",
            "tschechien",
            "babiš",
            "babis",
        ),
    ),
    (
        "SK",
        "Eslovaquia",
        "Slovakia",
        48.1,
        17.1,
        "eu",
        ("eslovaco", "eslovaca", "slovak", "bratislava", "fico", "slovaquie", "slowakei"),
    ),
    (
        "SI",
        "Eslovenia",
        "Slovenia",
        46.1,
        14.5,
        "eu",
        ("esloveno", "eslovena", "slovenian", "liubliana", "ljubljana", "slovénie", "slowenien"),
    ),
    ("HR", "Croacia", "Croatia", 45.8, 16.0, "eu", ("croata", "croatian", "zagreb", "croatie", "kroatien")),
    (
        "DK",
        "Dinamarca",
        "Denmark",
        55.7,
        12.6,
        "eu",
        (
            "danés",
            "danesa",
            "danish",
            "copenhague",
            "copenhagen",
            "danemark",
            "dänemark",
            "frederiksen",
            "groenlandia",
            "greenland",
            "grönland",
        ),
    ),
    (
        "FI",
        "Finlandia",
        "Finland",
        60.2,
        24.9,
        "eu",
        ("finlandés", "finlandesa", "finnish", "helsinki", "finlande", "finnland"),
    ),
    (
        "NO",
        "Noruega",
        "Norway",
        59.9,
        10.8,
        "eu",
        ("noruego", "noruega", "norwegian", "oslo", "norvège", "norwegen"),
    ),
    (
        "IS",
        "Islandia",
        "Iceland",
        64.1,
        -21.9,
        "eu",
        ("islandés", "icelandic", "reikiavik", "reykjavik", "islande"),
    ),
    (
        "EE",
        "Estonia",
        "Estonia",
        59.4,
        24.8,
        "eu",
        ("estonio", "estonia", "estonian", "tallin", "tallinn", "estonie", "estland"),
    ),
    (
        "LV",
        "Letonia",
        "Latvia",
        56.9,
        24.1,
        "eu",
        ("letón", "letona", "latvian", "riga", "lettonie", "lettland"),
    ),
    (
        "LT",
        "Lituania",
        "Lithuania",
        54.7,
        25.3,
        "eu",
        ("lituano", "lituana", "lithuanian", "vilna", "vilnius", "lituanie", "litauen"),
    ),
    ("LU", "Luxemburgo", "Luxembourg", 49.6, 6.1, "eu", ("luxemburgués", "luxembourgish", "luxembourg")),
    ("MT", "Malta", "Malta", 35.9, 14.5, "eu", ("maltés", "maltese", "la valeta", "valletta")),
    (
        "CY",
        "Chipre",
        "Cyprus",
        35.2,
        33.4,
        "eu",
        ("chipriota", "cypriot", "nicosia", "chypre", "zypern", "cyprus"),
    ),
    (
        "AL",
        "Albania",
        "Albania",
        41.3,
        19.8,
        "eu",
        ("albanés", "albanesa", "albanian", "tirana", "albanie", "albanien"),
    ),
    (
        "MK",
        "Macedonia del Norte",
        "North Macedonia",
        42.0,
        21.4,
        "eu",
        ("macedonio", "macedonian", "skopie", "skopje", "north macedonia"),
    ),
    ("ME", "Montenegro", "Montenegro", 42.4, 19.3, "eu", ("montenegrino", "montenegrin", "podgorica")),
    (
        "VN",
        "Vietnam",
        "Vietnam",
        21.0,
        105.8,
        "other_asia",
        ("vietnamita", "vietnamese", "hanói", "hanoi", "viêt nam", "viet nam"),
    ),
    (
        "TH",
        "Tailandia",
        "Thailand",
        13.8,
        100.5,
        "other_asia",
        ("tailandés", "tailandesa", "thai", "bangkok", "thaïlande", "thailand"),
    ),
    (
        "PH",
        "Filipinas",
        "Philippines",
        14.6,
        121.0,
        "other_asia",
        ("filipino", "filipina", "philippine", "manila", "marcos jr", "philippines", "philippinen"),
    ),
    (
        "MY",
        "Malasia",
        "Malaysia",
        3.1,
        101.7,
        "other_asia",
        ("malasio", "malaysian", "kuala lumpur", "malaisie", "malaysia", "anwar"),
    ),
    (
        "SG",
        "Singapur",
        "Singapore",
        1.3,
        103.8,
        "other_asia",
        ("singapurense", "singaporean", "singapour", "singapore", "singapur"),
    ),
    (
        "MM",
        "Birmania",
        "Myanmar",
        19.8,
        96.2,
        "other_asia",
        ("birmano", "birmana", "burmese", "myanmar", "naipyidó", "naypyidaw", "junta birmana"),
    ),
    (
        "KH",
        "Camboya",
        "Cambodia",
        11.6,
        104.9,
        "other_asia",
        ("camboyano", "cambodian", "phnom penh", "cambodge", "cambodia"),
    ),
    ("LK", "Sri Lanka", "Sri Lanka", 6.9, 79.9, "india", ("esrilanqués", "sri lankan", "colombo")),
    ("NP", "Nepal", "Nepal", 27.7, 85.3, "india", ("nepalí", "nepali", "nepalese", "katmandú", "kathmandu")),
    (
        "MN",
        "Mongolia",
        "Mongolia",
        47.9,
        106.9,
        "other_asia",
        ("mongol", "mongolian", "ulán bator", "ulaanbaatar", "mongolie"),
    ),
    (
        "CI",
        "Costa de Marfil",
        "Ivory Coast",
        6.8,
        -5.3,
        "africa",
        ("marfileño", "ivorian", "abiyán", "abidjan", "côte d'ivoire", "cote d'ivoire", "ivory coast"),
    ),
    (
        "CM",
        "Camerún",
        "Cameroon",
        3.9,
        11.5,
        "africa",
        ("camerunés", "cameroonian", "yaundé", "yaoundé", "cameroun", "cameroon", "biya"),
    ),
    (
        "TZ",
        "Tanzania",
        "Tanzania",
        -6.2,
        35.7,
        "africa",
        ("tanzano", "tanzanian", "dodoma", "dar es salaam", "tanzanie"),
    ),
    ("UG", "Uganda", "Uganda", 0.3, 32.6, "africa", ("ugandés", "ugandan", "kampala", "museveni", "ouganda")),
    ("RW", "Ruanda", "Rwanda", -1.9, 30.1, "africa", ("ruandés", "rwandan", "kigali", "kagame", "rwanda")),
    (
        "ZW",
        "Zimbabue",
        "Zimbabwe",
        -17.8,
        31.1,
        "africa",
        ("zimbabuense", "zimbabwean", "harare", "zimbabwe"),
    ),
    ("ZM", "Zambia", "Zambia", -15.4, 28.3, "africa", ("zambiano", "zambian", "lusaka", "zambie")),
    ("TD", "Chad", "Chad", 12.1, 15.0, "africa", ("chadiano", "chadian", "yamena", "n'djamena", "tchad")),
    (
        "CF",
        "República Centroafricana",
        "Central African Republic",
        4.4,
        18.6,
        "africa",
        ("centroafricano", "central african", "bangui", "rca", "centrafrique"),
    ),
    (
        "SS",
        "Sudán del Sur",
        "South Sudan",
        4.9,
        31.6,
        "africa",
        ("sursudanés", "south sudanese", "yuba", "juba", "south sudan", "soudan du sud"),
    ),
    ("ER", "Eritrea", "Eritrea", 15.3, 38.9, "africa", ("eritreo", "eritrean", "asmara", "érythrée")),
    ("MG", "Madagascar", "Madagascar", -18.9, 47.5, "africa", ("malgache", "malagasy", "antananarivo")),
    ("GN", "Guinea", "Guinea", 9.5, -13.7, "africa", ("guineano", "guinean", "conakry", "guinée")),
    ("GA", "Gabón", "Gabon", 0.4, 9.5, "africa", ("gabonés", "gabonese", "libreville", "gabon")),
    (
        "MR",
        "Mauritania",
        "Mauritania",
        18.1,
        -15.9,
        "africa",
        ("mauritano", "mauritanian", "nuakchot", "nouakchott", "mauritanie"),
    ),
    ("TG", "Togo", "Togo", 6.1, 1.2, "africa", ("togolés", "togolese", "lomé")),
    (
        "BJ",
        "Benín",
        "Benin",
        6.5,
        2.6,
        "africa",
        ("beninés", "beninese", "cotonú", "cotonou", "benin", "bénin"),
    ),
    ("GL", "Groenlandia", "Greenland", 64.2, -51.7, "eu", ("groenlandés", "greenlandic", "nuuk")),
]


@lru_cache(maxsize=1)
def countries() -> dict[str, Country]:
    out: dict[str, Country] = {}
    for iso2, es, en, lat, lon, bloc, aliases in _C:
        out[iso2] = Country(iso2, es, en, lat, lon, bloc, tuple(aliases))
    return out


# Instituciones y bloques (kind institution/bloc) — nombre canónico, aliases, país (o None), bloque
_INSTITUTIONS: list[tuple[str, str, tuple[str, ...], str | None]] = [
    (
        "institution",
        "Unión Europea",
        (
            "unión europea",
            "union europea",
            "european union",
            "ue",
            "eu",
            "bruselas",
            "comisión europea",
            "european commission",
            "von der leyen",
            "consejo europeo",
            "european council",
            "parlamento europeo",
            "european parliament",
            "eurocámara",
            "eurozona",
            "eurozone",
            "eurogrupo",
            "eurogroup",
            "union européenne",
            "europäische union",
            "unione europea",
        ),
        None,
    ),
    (
        "institution",
        "Banco Central Europeo",
        (
            "banco central europeo",
            "bce",
            "ecb",
            "european central bank",
            "lagarde",
            "banque centrale européenne",
            "ezb",
            "europäische zentralbank",
        ),
        None,
    ),
    (
        "institution",
        "Reserva Federal",
        ("reserva federal", "fed", "federal reserve", "fomc", "powell", "warsh", "réserve fédérale"),
        "US",
    ),
    (
        "institution",
        "Naciones Unidas",
        (
            "naciones unidas",
            "onu",
            "un ",
            "united nations",
            "consejo de seguridad",
            "security council",
            "asamblea general",
            "general assembly",
            "guterres",
            "unicef",
            "acnur",
            "unhcr",
            "unrwa",
            "nations unies",
            "vereinte nationen",
        ),
        None,
    ),
    ("institution", "OTAN", ("otan", "nato", "alianza atlántica", "atlantic alliance", "rutte"), None),
    (
        "institution",
        "Fondo Monetario Internacional",
        ("fondo monetario internacional", "fmi", "imf", "international monetary fund", "georgieva"),
        None,
    ),
    ("institution", "Banco Mundial", ("banco mundial", "world bank", "banque mondiale", "weltbank"), None),
    (
        "institution",
        "Organización Mundial de la Salud",
        ("organización mundial de la salud", "oms", "who", "world health organization", "tedros"),
        None,
    ),
    (
        "institution",
        "Organización Mundial del Comercio",
        ("organización mundial del comercio", "omc", "wto", "world trade organization"),
        None,
    ),
    ("institution", "OPEP", ("opep", "opec", "opep+", "opec+"), None),
    (
        "institution",
        "Corte Penal Internacional",
        (
            "corte penal internacional",
            "cpi",
            "icc",
            "international criminal court",
            "tribunal penal internacional",
        ),
        None,
    ),
    (
        "institution",
        "Corte Internacional de Justicia",
        ("corte internacional de justicia", "cij", "icj", "international court of justice"),
        None,
    ),
    ("institution", "G7", ("g7", "g-7", "grupo de los siete"), None),
    ("institution", "G20", ("g20", "g-20"), None),
    ("institution", "BRICS", ("brics", "brics+"), None),
    ("institution", "Unión Africana", ("unión africana", "african union", "union africaine"), None),
    ("institution", "ASEAN", ("asean",), None),
    ("institution", "Banco de Inglaterra", ("banco de inglaterra", "bank of england", "boe", "bailey"), "GB"),
    ("institution", "Banco de Japón", ("banco de japón", "bank of japan", "boj", "ueda"), "JP"),
    ("institution", "Banco de España", ("banco de españa", "bank of spain", "escrivá"), "ES"),
    (
        "institution",
        "Banco Popular de China",
        ("banco popular de china", "pboc", "people's bank of china"),
        "CN",
    ),
    (
        "institution",
        "Banco Central de Turquía",
        ("banco central de turquía", "cbrt", "tcmb", "central bank of turkey"),
        "TR",
    ),
    (
        "institution",
        "Gobierno de España",
        (
            "gobierno de españa",
            "moncloa",
            "consejo de ministros",
            "pedro sánchez",
            "sánchez",
            "psoe",
            "pp",
            "partido popular",
            "feijóo",
            "vox",
            "abascal",
            "sumar",
            "yolanda díaz",
            "junts",
            "puigdemont",
            "erc",
            "bildu",
            "pnv",
            "podemos",
        ),
        "ES",
    ),
    (
        "institution",
        "Congreso de los Diputados",
        ("congreso de los diputados", "congreso", "senado", "cortes generales"),
        "ES",
    ),
    (
        "institution",
        "Tribunal Supremo",
        (
            "tribunal supremo",
            "supremo",
            "tribunal constitucional",
            "audiencia nacional",
            "fiscal general",
            "cgpj",
        ),
        "ES",
    ),
    ("institution", "Boletín Oficial del Estado", ("boletín oficial del estado", "boe"), "ES"),
    (
        "institution",
        "Casa Blanca",
        (
            "casa blanca",
            "white house",
            "trump",
            "vance",
            "rubio",
            "hegseth",
            "bessent",
            "administración trump",
            "trump administration",
            "maga",
            "republicanos",
            "republicans",
            "gop",
            "demócratas",
            "democrats",
        ),
        "US",
    ),
    (
        "institution",
        "Congreso de EE. UU.",
        (
            "congreso de ee. uu.",
            "congress",
            "senado de ee. uu.",
            "senate",
            "cámara de representantes",
            "house of representatives",
            "capitolio",
            "capitol hill",
        ),
        "US",
    ),
    (
        "institution",
        "Tribunal Supremo de EE. UU.",
        ("tribunal supremo de ee. uu.", "supreme court", "scotus"),
        "US",
    ),
    ("institution", "Kremlin", ("kremlin", "kremlín", "putin", "lavrov", "peskov", "duma"), "RU"),
    (
        "institution",
        "Partido Comunista de China",
        (
            "partido comunista de china",
            "pcch",
            "chinese communist party",
            "ccp",
            "xi jinping",
            "wang yi",
            "politburó",
            "politburo",
            "zhongnanhai",
        ),
        "CN",
    ),
    (
        "institution",
        "Gobierno de Israel",
        (
            "gobierno de israel",
            "netanyahu",
            "knesset",
            "likud",
            "fdi",
            "idf",
            "mosad",
            "mossad",
            "ben gvir",
            "smotrich",
        ),
        "IL",
    ),
    ("institution", "Hamás", ("hamás", "hamas", "yihad islámica", "islamic jihad"), "PS"),
    ("institution", "Hezbolá", ("hezbolá", "hezbollah", "hizbulá"), "LB"),
    ("institution", "Hutíes", ("hutíes", "houthis", "huthi", "houthi", "ansar allah", "ansarolá"), "YE"),
    (
        "institution",
        "Gobierno de Francia",
        (
            "gobierno de francia",
            "macron",
            "elíseo",
            "élysée",
            "matignon",
            "asamblea nacional",
            "assemblée nationale",
            "rassemblement national",
            "reagrupamiento nacional",
            "le pen",
            "bardella",
            "mélenchon",
        ),
        "FR",
    ),
    (
        "institution",
        "Gobierno de Alemania",
        (
            "gobierno de alemania",
            "merz",
            "bundestag",
            "cdu",
            "csu",
            "spd",
            "afd",
            "alternativa para alemania",
            "los verdes",
            "die grünen",
            "cancillería alemana",
        ),
        "DE",
    ),
    (
        "institution",
        "Gobierno del Reino Unido",
        (
            "gobierno del reino unido",
            "starmer",
            "downing street",
            "westminster",
            "labour",
            "laborista",
            "laboristas",
            "tories",
            "conservadores británicos",
            "reform uk",
            "farage",
        ),
        "GB",
    ),
    (
        "institution",
        "Gobierno de Italia",
        (
            "gobierno de italia",
            "meloni",
            "palazzo chigi",
            "fratelli d'italia",
            "hermanos de italia",
            "salvini",
            "liga",
        ),
        "IT",
    ),
    (
        "institution",
        "Gobierno de Ucrania",
        ("gobierno de ucrania", "zelenski", "zelensky", "zelenskyy", "rada", "sybiha"),
        "UA",
    ),
    (
        "institution",
        "Gobierno de Turquía",
        ("gobierno de turquía", "erdogan", "erdoğan", "akp", "chp", "imamoglu", "i̇mamoğlu"),
        "TR",
    ),
    (
        "institution",
        "Gobierno de Irán",
        (
            "gobierno de irán",
            "jamenei",
            "khamenei",
            "pezeshkian",
            "araghchi",
            "guardianes de la revolución",
            "irgc",
        ),
        "IR",
    ),
    ("institution", "Gobierno de India", ("gobierno de india", "modi", "bjp", "jaishankar"), "IN"),
    ("institution", "Gobierno de Brasil", ("gobierno de brasil", "lula", "planalto", "bolsonaro"), "BR"),
    (
        "institution",
        "Gobierno de México",
        ("gobierno de méxico", "sheinbaum", "morena", "palacio nacional"),
        "MX",
    ),
    (
        "institution",
        "Gobierno de Argentina",
        ("gobierno de argentina", "milei", "casa rosada", "kirchner", "peronismo"),
        "AR",
    ),
    (
        "institution",
        "Gobierno de Arabia Saudí",
        ("gobierno de arabia saudí", "bin salmán", "bin salman", "mbs", "aramco"),
        "SA",
    ),
    (
        "institution",
        "Comisión Europea",
        (
            "comisión europea",
            "european commission",
            "von der leyen",
            "kallas",
            "šefčovič",
            "sefcovic",
            "dombrovskis",
        ),
        None,
    ),
    (
        "institution",
        "Agencia Europea de Medicamentos",
        ("agencia europea de medicamentos", "ema", "european medicines agency"),
        None,
    ),
    ("institution", "FDA", ("fda", "food and drug administration"), "US"),
    (
        "institution",
        "Agencia Internacional de la Energía",
        ("agencia internacional de la energía", "aie", "iea", "international energy agency"),
        None,
    ),
    ("institution", "OIEA", ("oiea", "iaea", "agencia internacional de la energía atómica", "grossi"), None),
    ("institution", "Eurostat", ("eurostat",), None),
    ("institution", "INE", ("instituto nacional de estadística", "ine"), "ES"),
    ("institution", "SEC", ("sec", "securities and exchange commission"), "US"),
    ("institution", "Mercosur", ("mercosur", "mercosul"), None),
    (
        "institution",
        "Consejo de Cooperación del Golfo",
        ("consejo de cooperación del golfo", "ccg", "gcc", "gulf cooperation council"),
        None,
    ),
    ("institution", "Liga Árabe", ("liga árabe", "arab league"), None),
    ("company", "Nvidia", ("nvidia",), "US"),
    ("company", "Apple", ("apple", "iphone"), "US"),
    ("company", "Microsoft", ("microsoft",), "US"),
    ("company", "Alphabet", ("alphabet", "google"), "US"),
    ("company", "Meta", ("meta platforms", "facebook", "instagram", "zuckerberg"), "US"),
    ("company", "Amazon", ("amazon", "bezos"), "US"),
    ("company", "Tesla", ("tesla", "musk", "spacex", "starlink"), "US"),
    ("company", "OpenAI", ("openai", "chatgpt", "altman"), "US"),
    ("company", "Anthropic", ("anthropic", "claude"), "US"),
    ("company", "TSMC", ("tsmc",), "TW"),
    ("company", "Huawei", ("huawei",), "CN"),
    ("company", "BYD", ("byd",), "CN"),
    ("company", "Telefónica", ("telefónica", "telefonica"), "ES"),
    ("company", "Iberdrola", ("iberdrola",), "ES"),
    ("company", "Repsol", ("repsol",), "ES"),
    ("company", "Santander", ("banco santander", "santander"), "ES"),
    ("company", "BBVA", ("bbva",), "ES"),
    ("company", "Inditex", ("inditex", "zara"), "ES"),
    ("company", "Pfizer", ("pfizer",), "US"),
    ("company", "Novo Nordisk", ("novo nordisk", "ozempic", "wegovy"), "DK"),
    ("company", "Eli Lilly", ("eli lilly", "lilly", "mounjaro", "zepbound"), "US"),
    ("company", "Boeing", ("boeing",), "US"),
    ("company", "Airbus", ("airbus",), "FR"),
    ("company", "Gazprom", ("gazprom",), "RU"),
    ("company", "Rosneft", ("rosneft",), "RU"),
]

_TOPICS: list[tuple[str, tuple[str, ...]]] = [
    (
        "Inteligencia artificial",
        (
            "inteligencia artificial",
            "artificial intelligence",
            " ia ",
            " ai ",
            "chatgpt",
            "modelos de lenguaje",
            "llm",
            "ai act",
            "deepseek",
        ),
    ),
    (
        "Migración",
        (
            "migración",
            "migration",
            "inmigración",
            "immigration",
            "migrantes",
            "migrants",
            "refugiados",
            "refugees",
            "asilo",
            "asylum",
            "deportaciones",
            "deportations",
            "frontera",
            "border",
            "pateras",
            "canarias",
        ),
    ),
    (
        "Aranceles y comercio",
        (
            "aranceles",
            "tariffs",
            "tariff",
            "arancel",
            "guerra comercial",
            "trade war",
            "comercio",
            "trade deal",
            "acuerdo comercial",
        ),
    ),
    (
        "Inflación y tipos",
        (
            "inflación",
            "inflation",
            "ipc",
            "cpi",
            "tipos de interés",
            "interest rates",
            "rate cut",
            "rate hike",
            "subida de tipos",
            "bajada de tipos",
            "política monetaria",
            "monetary policy",
        ),
    ),
    (
        "Energía",
        (
            "petróleo",
            "oil",
            "brent",
            "gas",
            "gnl",
            "lng",
            "energía",
            "energy",
            "renovables",
            "renewables",
            "nuclear",
            "eólica",
            "solar",
            "electricidad",
            "apagón",
            "blackout",
        ),
    ),
    (
        "Defensa y rearme",
        (
            "defensa",
            "defence",
            "defense",
            "gasto militar",
            "military spending",
            "rearme",
            "rearmament",
            "ejército",
            "army",
            "misiles",
            "missiles",
            "drones",
            "otan",
            "nato",
        ),
    ),
    (
        "Elecciones",
        (
            "elecciones",
            "election",
            "elections",
            "comicios",
            "votación",
            "vote",
            "encuesta",
            "poll",
            "sondeo",
            "campaña electoral",
            "candidato",
            "candidate",
        ),
    ),
    (
        "Sanidad y salud pública",
        (
            "sanidad",
            "salud pública",
            "public health",
            "vacuna",
            "vaccine",
            "oms",
            "who",
            "pandemia",
            "pandemic",
            "hospital",
            "hospitales",
            "medicamentos",
            "drugs",
            "ensayo clínico",
            "clinical trial",
            "ema",
            "fda",
            "envejecimiento",
            "ageing",
            "aging",
        ),
    ),
    (
        "Clima",
        (
            "cambio climático",
            "climate change",
            "cop30",
            "cop31",
            "emisiones",
            "emissions",
            "calentamiento",
            "warming",
            "ola de calor",
            "heatwave",
            "sequía",
            "drought",
            "inundaciones",
            "floods",
            "dana",
            "huracán",
            "hurricane",
            "incendios",
            "wildfires",
        ),
    ),
    (
        "Vivienda",
        (
            "vivienda",
            "housing",
            "alquiler",
            "rent",
            "hipoteca",
            "mortgage",
            "precio de la vivienda",
            "house prices",
        ),
    ),
    (
        "Deuda y fiscalidad",
        (
            "deuda",
            "debt",
            "déficit",
            "deficit",
            "presupuestos",
            "budget",
            "impuestos",
            "taxes",
            "fiscal",
            "prima de riesgo",
            "bond yields",
            "rating",
            "moody's",
            "s&p",
            "fitch",
        ),
    ),
    ("Criptomonedas", ("bitcoin", "cripto", "crypto", "ethereum", "stablecoin")),
    ("Sanciones", ("sanciones", "sanctions", "embargo", "congelación de activos", "frozen assets")),
    (
        "Terrorismo y seguridad",
        (
            "atentado",
            "attack",
            "terrorismo",
            "terrorism",
            "yihadista",
            "jihadist",
            "estado islámico",
            "islamic state",
            "isis",
            "daesh",
            "al qaeda",
        ),
    ),
    (
        "Justicia y Estado de derecho",
        (
            "sentencia",
            "ruling",
            "tribunal",
            "court",
            "juez",
            "judge",
            "fiscalía",
            "prosecutor",
            "imputado",
            "indicted",
            "corrupción",
            "corruption",
            "amnistía",
            "amnesty",
            "estado de derecho",
            "rule of law",
        ),
    ),
    (
        "Alto el fuego y negociaciones",
        (
            "alto el fuego",
            "ceasefire",
            "tregua",
            "truce",
            "negociaciones de paz",
            "peace talks",
            "acuerdo de paz",
            "peace deal",
            "rehenes",
            "hostages",
            "mediación",
            "mediation",
        ),
    ),
]


@dataclass(frozen=True)
class Mention:
    key: str  # p.ej. "country:ES", "institution:Reserva Federal", "topic:Energía"
    kind: str
    name: str
    country: str | None
    count: int


# Alias cortos y ambiguos que solo cuentan si aparecen en mayúsculas en el texto original
_CASE_SENSITIVE = {
    "ue",
    "eu",
    "un",
    "ine",
    "boe",
    "fed",
    "sec",
    "ia",
    "ai",
    "pp",
    "cpi",
    "ipc",
    "bce",
    "ecb",
    "fmi",
    "imf",
    "oms",
    "who",
    "omc",
    "wto",
    "cij",
    "icj",
    "aie",
    "iea",
    "ema",
    "fda",
    "gop",
    "isis",
    "rsf",
    "rca",
    "drc",
    "rdc",
    "mbs",
    "boj",
    "gcc",
    "ccg",
    "uk",
    "usa",
    "idf",
    "fdi",
    "irgc",
    "akp",
    "chp",
    "bjp",
    "cdu",
    "csu",
    "spd",
    "afd",
    "erc",
    "pnv",
    "byd",
    "meta",
    "apple",
    "liga",
    "lilly",
    "vox",
    "sumar",
    "junts",
    "morena",
    "reform uk",
    "labour",
    "kast",
    "petro",
    "ruto",
    "biya",
    "modi",
    "lula",
    "musk",
    "meloni",
    "merz",
    "ortega",
    "sandu",
    "tusk",
    "fico",
    "dodik",
    "carney",
    "anwar",
    "abiy",
    "noboa",
    "ueda",
    "bailey",
    "powell",
    "warsh",
    "rutte",
    "tedros",
    "grossi",
    "guterres",
    "peskov",
    "lavrov",
    "bezos",
    "altman",
    "claude",
    "zara",
}


@lru_cache(maxsize=1)
def _compiled() -> list[tuple[str, str, str, str | None, str, re.Pattern]]:
    """Lista de (key, kind, name, country, alias_normalizado, regex)."""
    items: list[tuple[str, str, str, str | None, str]] = []
    for c in countries().values():
        for alias in (c.name_es, c.name_en, *c.aliases):
            items.append((f"country:{c.iso2}", "country", c.name_es, c.iso2, alias))
    for kind, name, aliases, country in _INSTITUTIONS:
        for alias in (name, *aliases):
            items.append((f"{kind}:{name}", kind, name, country, alias))
    for name, aliases in _TOPICS:
        for alias in aliases:
            items.append((f"topic:{name}", "topic", name, None, alias))
    out = []
    seen: set[tuple[str, str]] = set()
    for key, kind, name, country, alias in items:
        a = normalize_text(alias.strip())
        if not a or (key, a) in seen:
            continue
        seen.add((key, a))
        # límite de palabra tolerante a puntos ("ee. uu.") y guiones
        rx = re.compile(r"(?<![\w])" + re.escape(a) + r"(?![\w])")
        out.append((key, kind, name, country, a, rx))
    return out


def _case_ok(alias: str, *originals: str) -> bool:
    """Para siglas y apellidos ambiguos: exigir mayúscula inicial o todo mayúsculas en el texto original."""
    variants = {alias.upper(), alias.capitalize(), alias.title()}
    for v in variants:
        rx = re.compile(r"(?<![\w])" + re.escape(v) + r"(?![\w])")
        if any(rx.search(o) for o in originals if o):
            return True
    return False


def find_mentions(text: str, title: str | None = None) -> list[Mention]:
    """Devuelve menciones de entidades con recuento; el título cuenta triple."""
    if not text and not title:
        return []
    body = text or ""
    ttl = title or ""
    norm_body = normalize_text(body)
    norm_title = normalize_text(ttl)
    counts: dict[str, list] = {}
    for key, kind, name, country, alias, rx in _compiled():
        n_body = len(rx.findall(norm_body))
        n_title = len(rx.findall(norm_title))
        if n_body + n_title == 0:
            continue
        if alias in _CASE_SENSITIVE and not _case_ok(alias, body, ttl):
            continue
        entry = counts.setdefault(key, [kind, name, country, 0])
        entry[3] += n_body + 3 * n_title
    out = [Mention(k, v[0], v[1], v[2], v[3]) for k, v in counts.items()]
    out.sort(key=lambda m: -m.count)
    return out


def countries_from_mentions(mentions: list[Mention], max_n: int = 4) -> list[str]:
    """Países principales: explícitos primero; instituciones con país aportan la mitad."""
    score: dict[str, float] = {}
    for m in mentions:
        if m.kind == "country" and m.country:
            score[m.country] = score.get(m.country, 0) + m.count
        elif m.country and m.kind in ("institution", "company"):
            score[m.country] = score.get(m.country, 0) + 0.5 * m.count
    ranked = sorted(score.items(), key=lambda kv: -kv[1])
    if not ranked:
        return []
    top = ranked[0][1]
    return [c for c, s in ranked[:max_n] if s >= max(1.0, 0.2 * top)]


def principal_keys(mentions: list[Mention], max_n: int = 5) -> list[str]:
    """Claves de entidad principales (países + instituciones/empresas, sin temas) para el clustering."""
    keys = [m.key for m in mentions if m.kind in ("country", "institution", "company")]
    return keys[:max_n]


def topics_from_mentions(mentions: list[Mention]) -> list[str]:
    return [m.name for m in mentions if m.kind == "topic"][:4]


DOMAIN_RULES: list[tuple[str, tuple[str, ...]]] = [
    (
        "conflict",
        (
            "guerra",
            "war",
            "ataque",
            "attack",
            "bombardeo",
            "strike",
            "misil",
            "missile",
            "ofensiva",
            "offensive",
            "tropas",
            "troops",
            "alto el fuego",
            "ceasefire",
            "ejército",
            "military",
            "drones",
            "frente",
            "front line",
            "rehenes",
            "hostages",
            "muertos",
            "killed",
            "combates",
            "fighting",
        ),
    ),
    (
        "economy",
        (
            "inflación",
            "inflation",
            "pib",
            "gdp",
            "tipos",
            "rates",
            "bce",
            "ecb",
            "fed",
            "bolsa",
            "stocks",
            "mercado",
            "market",
            "aranceles",
            "tariffs",
            "deuda",
            "debt",
            "déficit",
            "deficit",
            "empleo",
            "jobs",
            "paro",
            "unemployment",
            "banco",
            "bank",
            "euro",
            "dólar",
            "dollar",
            "petróleo",
            "oil",
            "precio",
            "price",
            "exportaciones",
            "exports",
        ),
    ),
    (
        "health",
        (
            "salud",
            "health",
            "sanidad",
            "hospital",
            "vacuna",
            "vaccine",
            "oms",
            "who",
            "epidemia",
            "epidemic",
            "brote",
            "outbreak",
            "medicamento",
            "drug",
            "ensayo clínico",
            "clinical trial",
            "cáncer",
            "cancer",
            "gripe",
            "flu",
            "covid",
            "ébola",
            "ebola",
            "mpox",
            "cólera",
            "cholera",
        ),
    ),
    (
        "technology",
        (
            "inteligencia artificial",
            "artificial intelligence",
            "ai ",
            "ia ",
            "chip",
            "semiconductor",
            "ciberataque",
            "cyberattack",
            "software",
            "nvidia",
            "openai",
            "tecnológica",
            "tech",
            "startup",
            "satélite",
            "satellite",
            "cohete",
            "rocket",
            "cuántic",
            "quantum",
        ),
    ),
    (
        "environment",
        (
            "clima",
            "climate",
            "emisiones",
            "emissions",
            "temperatura",
            "temperature",
            "incendio",
            "wildfire",
            "inundación",
            "flood",
            "sequía",
            "drought",
            "huracán",
            "hurricane",
            "terremoto",
            "earthquake",
            "biodiversidad",
            "biodiversity",
            "contaminación",
            "pollution",
        ),
    ),
    (
        "law",
        (
            "tribunal",
            "court",
            "sentencia",
            "ruling",
            "juez",
            "judge",
            "fiscal",
            "prosecutor",
            "juicio",
            "trial",
            "condena",
            "sentenced",
            "ley",
            "law",
            "decreto",
            "decree",
            "constitución",
            "constitution",
            "reforma",
            "reform",
            "amnistía",
            "amnesty",
        ),
    ),
    (
        "society",
        (
            "protesta",
            "protest",
            "manifestación",
            "demonstration",
            "huelga",
            "strike",
            "educación",
            "education",
            "universidad",
            "university",
            "iglesia",
            "church",
            "papa",
            "pope",
            "vaticano",
            "vatican",
            "feminismo",
            "feminist",
            "lgtb",
            "racismo",
            "racism",
        ),
    ),
    (
        "politics",
        (
            "gobierno",
            "government",
            "presidente",
            "president",
            "primer ministro",
            "prime minister",
            "ministro",
            "minister",
            "parlamento",
            "parliament",
            "elecciones",
            "election",
            "partido",
            "party",
            "oposición",
            "opposition",
            "coalición",
            "coalition",
            "moción",
            "votación",
            "vote",
            "cumbre",
            "summit",
            "diplomacia",
            "diplomatic",
            "embajador",
            "ambassador",
            "sanciones",
            "sanctions",
            "tratado",
            "treaty",
        ),
    ),
]


def classify_domain(text: str) -> str:
    t = " " + normalize_text(text) + " "
    best, best_score = "politics", 0
    for domain, kws in DOMAIN_RULES:
        s = 0
        for kw in kws:
            k = normalize_text(kw)
            if k.startswith(" ") or k.endswith(" "):
                s += t.count(k)
            else:
                s += len(re.findall(r"(?<![\w])" + re.escape(k), t))
        if s > best_score:
            best, best_score = domain, s
    return best
