"""Datos semilla codificados a mano: casos históricos (ARCHIVO), mapa argumental de la RBU y genealogía de la
libertad (ÁGORA). Están marcados como semilla: se deben verificar antes de citarlos en un trabajo.
"""

from __future__ import annotations

SEED_NOTE = (
    "Semilla codificada por el constructor (2026-09). Verificar fechas y cifras en la fuente antes de citar."
)

# name, category, start, end, countries, variables, outcome, duration_months, summary, sources
HISTORICAL_CASES: list[dict] = [
    # ── Crisis de deuda soberana ──
    dict(
        name="Argentina 2001: default y fin de la convertibilidad",
        category="debt_crisis",
        start_date="2001-12-01",
        end_date="2005-06-01",
        countries=["AR"],
        variables={
            "exchange_regime": "peg",
            "imf_program": True,
            "banking_crisis": True,
            "political_collapse": True,
            "external_debt_gdp": ">50%",
        },
        outcome="Default de ~93.000 M USD, fin del peg 1:1, caída del PIB ~11% en 2002, reestructuración con quita ~65% en 2005.",
        duration_months=42,
        summary="Régimen de convertibilidad rígido, déficit fiscal persistente y fuga de capitales terminaron en corralito, cinco presidentes en dos semanas y el mayor default soberano hasta entonces.",
        sources=["Reinhart & Rogoff (2009) This Time Is Different", "FMI, Informe de evaluación 2004"],
    ),
    dict(
        name="Grecia 2010-2018: crisis de deuda y rescates",
        category="debt_crisis",
        start_date="2010-04-01",
        end_date="2018-08-20",
        countries=["GR"],
        variables={
            "exchange_regime": "currency_union",
            "imf_program": True,
            "banking_crisis": True,
            "political_collapse": False,
            "external_debt_gdp": ">100%",
        },
        outcome="Tres programas de rescate (~289.000 M EUR), reestructuración privada (PSI) en 2012 con quita ~53%, PIB −25%, salida del programa en 2018.",
        duration_months=100,
        summary="Déficit oculto revelado en 2009, pérdida de acceso a mercados y ajuste dentro del euro sin devaluación posible.",
        sources=["Comisión Europea, programas MEDE", "FMI (2013) evaluación ex post"],
    ),
    dict(
        name="México 1994: crisis del Tequila",
        category="debt_crisis",
        start_date="1994-12-20",
        end_date="1996-12-31",
        countries=["MX"],
        variables={
            "exchange_regime": "crawling_peg",
            "imf_program": True,
            "banking_crisis": True,
            "political_collapse": False,
            "external_debt_gdp": "<50%",
        },
        outcome="Devaluación del peso ~50%, rescate de EE. UU. y FMI (~50.000 M USD), PIB −6% en 1995, recuperación rápida por exportaciones.",
        duration_months=24,
        summary="Déficit por cuenta corriente financiado con tesobonos a corto plazo en dólares; año electoral y shock político (Chiapas, asesinato de Colosio).",
        sources=["Banco de México", "FMI"],
    ),
    dict(
        name="Crisis asiática 1997 (Tailandia)",
        category="debt_crisis",
        start_date="1997-07-02",
        end_date="1999-12-31",
        countries=["TH", "ID", "KR"],
        variables={
            "exchange_regime": "peg",
            "imf_program": True,
            "banking_crisis": True,
            "political_collapse": True,
            "external_debt_gdp": "<50%",
        },
        outcome="Contagio regional, caída de Suharto en Indonesia (1998), programas del FMI en TH/ID/KR, recuperación en V desde 1999.",
        duration_months=30,
        summary="Endeudamiento privado a corto en dólares con tipos de cambio fijos; ataque especulativo al baht y contagio.",
        sources=["Radelet & Sachs (1998)", "FMI"],
    ),
    dict(
        name="Rusia 1998: default y devaluación del rublo",
        category="debt_crisis",
        start_date="1998-08-17",
        end_date="1999-12-31",
        countries=["RU"],
        variables={
            "exchange_regime": "band",
            "imf_program": True,
            "banking_crisis": True,
            "political_collapse": False,
            "commodity_shock": True,
        },
        outcome="Default de deuda interna (GKO), devaluación ~70%, quiebra de LTCM en EE. UU.; recuperación desde 1999 con el petróleo.",
        duration_months=16,
        summary="Caída del petróleo tras la crisis asiática, déficit fiscal y deuda a corto en rublos con banda cambiaria insostenible.",
        sources=["Chiodo & Owyang (2002), Fed St. Louis"],
    ),
    dict(
        name="Líbano 2020: default soberano y colapso bancario",
        category="debt_crisis",
        start_date="2020-03-07",
        end_date=None,
        countries=["LB"],
        variables={
            "exchange_regime": "peg",
            "imf_program": False,
            "banking_crisis": True,
            "political_collapse": True,
            "external_debt_gdp": ">150%",
        },
        outcome="Primer default de la historia del país, libra −95%, hiperinflación, sin acuerdo con el FMI cerrado a 2025.",
        duration_months=None,
        summary="Esquema Ponzi financiero del banco central con depósitos en dólares; explosión del puerto de Beirut (2020) agravó la crisis política.",
        sources=["Banco Mundial (2021) Lebanon Economic Monitor"],
    ),
    dict(
        name="Sri Lanka 2022: default y caída del Gobierno",
        category="debt_crisis",
        start_date="2022-04-12",
        end_date="2024-12-31",
        countries=["LK"],
        variables={
            "exchange_regime": "managed",
            "imf_program": True,
            "banking_crisis": False,
            "political_collapse": True,
            "external_debt_gdp": ">100%",
        },
        outcome="Default externo, protestas masivas, huida del presidente Rajapaksa (julio 2022), programa FMI 2023 y reestructuración 2024.",
        duration_months=32,
        summary="Recortes fiscales de 2019, prohibición de fertilizantes químicos, colapso del turismo con la pandemia y deuda bilateral con China.",
        sources=["FMI (2023) EFF Sri Lanka"],
    ),
    dict(
        name="Islandia 2008: colapso bancario",
        category="debt_crisis",
        start_date="2008-10-06",
        end_date="2011-08-31",
        countries=["IS"],
        variables={
            "exchange_regime": "float",
            "imf_program": True,
            "banking_crisis": True,
            "political_collapse": True,
            "bank_assets_gdp": ">900%",
        },
        outcome="Quiebra de los tres grandes bancos, controles de capital hasta 2017, referéndums Icesave, recuperación desde 2011.",
        duration_months=34,
        summary="Bancos con activos de ~10 veces el PIB financiados en mercados mayoristas; el Estado no pudo rescatarlos y dejó caer la deuda externa bancaria.",
        sources=["FMI (2012) Iceland ex post evaluation"],
    ),
    dict(
        name="Irlanda 2010: rescate por la banca",
        category="debt_crisis",
        start_date="2010-11-21",
        end_date="2013-12-15",
        countries=["IE"],
        variables={
            "exchange_regime": "currency_union",
            "imf_program": True,
            "banking_crisis": True,
            "political_collapse": True,
        },
        outcome="Rescate de 85.000 M EUR, garantía bancaria de 2008 convertida en deuda pública (déficit 32% del PIB en 2010), salida limpia en 2013.",
        duration_months=37,
        summary="Burbuja inmobiliaria y garantía estatal general de los pasivos bancarios.",
        sources=["Comisión Europea", "Honohan Report (2010)"],
    ),
    dict(
        name="Venezuela 2017: default y colapso económico",
        category="debt_crisis",
        start_date="2017-11-13",
        end_date=None,
        countries=["VE"],
        variables={
            "exchange_regime": "multiple",
            "imf_program": False,
            "banking_crisis": False,
            "political_collapse": False,
            "commodity_shock": True,
            "sanctions": True,
        },
        outcome="Default de deuda soberana y de PDVSA, PIB −75% (2013-2020), hiperinflación, emigración de más de 7 millones.",
        duration_months=None,
        summary="Dependencia petrolera, controles de precios y cambio, caída de la producción de crudo y sanciones desde 2017.",
        sources=["FMI WEO", "ACNUR/R4V"],
    ),
    # ── Hiperinflación ──
    dict(
        name="Alemania 1923: hiperinflación de Weimar",
        category="hyperinflation",
        start_date="1922-08-01",
        end_date="1923-11-15",
        countries=["DE"],
        variables={
            "cause": "war_reparations_monetization",
            "peak_monthly_inflation": "29.500%",
            "stabilization": "new_currency",
        },
        outcome="Rentenmark (nov. 1923) y Plan Dawes (1924) estabilizan; destrucción del ahorro de la clase media.",
        duration_months=16,
        summary="Monetización del déficit tras la ocupación del Ruhr y las reparaciones de Versalles.",
        sources=["Sargent (1982) The Ends of Four Big Inflations"],
    ),
    dict(
        name="Zimbabue 2007-2009: hiperinflación",
        category="hyperinflation",
        start_date="2007-03-01",
        end_date="2009-02-01",
        countries=["ZW"],
        variables={
            "cause": "land_reform_monetization",
            "peak_monthly_inflation": "7,96e10%",
            "stabilization": "dollarization",
        },
        outcome="Dolarización de facto en 2009; el dólar zimbabuense se abandona.",
        duration_months=23,
        summary="Colapso agrícola tras la reforma agraria, déficit monetizado y sanciones.",
        sources=["Hanke & Kwok (2009) Cato Journal"],
    ),
    dict(
        name="Argentina 1989-1990: hiperinflación",
        category="hyperinflation",
        start_date="1989-05-01",
        end_date="1991-04-01",
        countries=["AR"],
        variables={
            "cause": "fiscal_monetization",
            "peak_monthly_inflation": "197%",
            "stabilization": "currency_board",
        },
        outcome="Ley de Convertibilidad (1991) fija 1 peso = 1 dólar; estabilidad hasta 2001.",
        duration_months=23,
        summary="Déficit crónico, pérdida de confianza y fuga al dólar; Alfonsín adelanta la entrega del poder a Menem.",
        sources=["Kiguel (1991)"],
    ),
    dict(
        name="Venezuela 2016-2021: hiperinflación",
        category="hyperinflation",
        start_date="2016-11-01",
        end_date="2021-12-31",
        countries=["VE"],
        variables={
            "cause": "fiscal_monetization_oil_collapse",
            "peak_monthly_inflation": ">200%",
            "stabilization": "de_facto_dollarization",
        },
        outcome="Dolarización de facto y liberalización parcial desde 2019 redujeron la inflación sin programa formal.",
        duration_months=61,
        summary="Financiación del déficit por el BCV con caída de ingresos petroleros y sanciones.",
        sources=["Asamblea Nacional (índice de precios)", "FMI"],
    ),
    dict(
        name="Turquía 2021-2023: crisis de la lira e inflación",
        category="hyperinflation",
        start_date="2021-09-01",
        end_date="2024-12-31",
        countries=["TR"],
        variables={
            "cause": "unorthodox_rate_cuts",
            "peak_annual_inflation": "85% (oct. 2022)",
            "stabilization": "orthodox_turn_2023",
        },
        outcome="Giro ortodoxo tras las elecciones de 2023 (Şimşek/Erkan): tipo oficial del 8,5% al 50%; inflación desacelera desde 2024.",
        duration_months=40,
        summary="Recortes de tipos con inflación creciente por presión presidencial; depreciación de la lira y dolarización.",
        sources=["TCMB", "TÜİK"],
    ),
    # ── Guerras comerciales ──
    dict(
        name="Smoot-Hawley 1930",
        category="trade_war",
        start_date="1930-06-17",
        end_date="1934-06-12",
        countries=["US"],
        variables={
            "tariff_scope": "broad",
            "retaliation": True,
            "wto_gatt_framework": False,
            "outcome_type": "reversal",
        },
        outcome="Represalias de Canadá y Europa, comercio mundial −66% (1929-34), Reciprocal Trade Agreements Act (1934) revierte la política.",
        duration_months=48,
        summary="Arancel general en plena Gran Depresión; caso canónico de represalia en cadena.",
        sources=["Irwin (2011) Peddling Protectionism"],
    ),
    dict(
        name="EE. UU.–Japón 1985-1991: Plaza y semiconductores",
        category="trade_war",
        start_date="1985-09-22",
        end_date="1991-08-01",
        countries=["US", "JP"],
        variables={
            "tariff_scope": "sectoral",
            "retaliation": False,
            "wto_gatt_framework": True,
            "outcome_type": "managed_trade",
        },
        outcome="Acuerdo del Plaza (yen +50%), acuerdo de semiconductores (1986) y cuotas voluntarias de exportación; burbuja japonesa y estancamiento posterior.",
        duration_months=71,
        summary="Déficit comercial de EE. UU. y presión sobre Japón mediante coordinación cambiaria y acuerdos sectoriales.",
        sources=["Frankel (2015)", "Irwin (2017) Clashing over Commerce"],
    ),
    dict(
        name="Guerra comercial EE. UU.–China 2018-2020",
        category="trade_war",
        start_date="2018-07-06",
        end_date="2020-01-15",
        countries=["US", "CN"],
        variables={
            "tariff_scope": "broad",
            "retaliation": True,
            "wto_gatt_framework": True,
            "outcome_type": "partial_deal",
        },
        outcome="Aranceles sobre ~360.000 M USD de importaciones chinas y represalias; acuerdo de Fase Uno (enero 2020) con compromisos de compra incumplidos.",
        duration_months=18,
        summary="Secciones 301 y 232; desviación de comercio hacia Vietnam y México; los aranceles se mantuvieron tras el acuerdo.",
        sources=["PIIE, Bown (2021) US-China Trade War Tariffs chart"],
    ),
    dict(
        name="Aranceles al acero de EE. UU. 2002",
        category="trade_war",
        start_date="2002-03-05",
        end_date="2003-12-04",
        countries=["US"],
        variables={
            "tariff_scope": "sectoral",
            "retaliation": True,
            "wto_gatt_framework": True,
            "outcome_type": "reversal",
        },
        outcome="OMC declara ilegales las salvaguardias; la UE amenaza represalias selectivas y Bush retira los aranceles en 21 meses.",
        duration_months=21,
        summary="Salvaguardias del 8-30% al acero; coste neto en empleo de industrias consumidoras de acero.",
        sources=["OMC DS248", "USITC (2003)"],
    ),
    dict(
        name="Guerra del pollo 1962-1964 (EE. UU.–CEE)",
        category="trade_war",
        start_date="1962-07-01",
        end_date="1964-01-01",
        countries=["US", "DE", "FR"],
        variables={
            "tariff_scope": "sectoral",
            "retaliation": True,
            "wto_gatt_framework": True,
            "outcome_type": "entrenched",
        },
        outcome="EE. UU. impone el «chicken tax» del 25% a camionetas ligeras, aún vigente.",
        duration_months=18,
        summary="Aranceles de la CEE al pollo estadounidense; represalia estadounidense que sobrevivió al conflicto original.",
        sources=["GATT", "Irwin (2017)"],
    ),
    # ── Sanciones ──
    dict(
        name="Sanciones a Irán 2012-2015 → JCPOA",
        category="sanctions",
        start_date="2012-01-01",
        end_date="2016-01-16",
        countries=["IR", "US"],
        variables={
            "type": "financial_oil_secondary",
            "multilateral": True,
            "target_behavior": "nuclear_program",
            "outcome_type": "negotiated_deal",
        },
        outcome="Exportaciones de crudo −50%, PIB −6% (2012), acuerdo nuclear (JCPOA) en 2015; EE. UU. se retira en 2018.",
        duration_months=48,
        summary="Sanciones petroleras y financieras coordinadas (UE, EE. UU., ONU) con exclusión de SWIFT.",
        sources=["CRS (2016) Iran Sanctions", "FMI"],
    ),
    dict(
        name="Sanciones a Rusia 2014 (Crimea/Donbás)",
        category="sanctions",
        start_date="2014-03-17",
        end_date="2022-02-23",
        countries=["RU"],
        variables={
            "type": "targeted_sectoral",
            "multilateral": True,
            "target_behavior": "territorial_annexation",
            "outcome_type": "no_behavior_change",
        },
        outcome="Sin reversión de la anexión; PIB −2% (2015) combinado con caída del petróleo; sustitución de importaciones y 'fortaleza Rusia'.",
        duration_months=95,
        summary="Sanciones sectoriales (finanzas, energía, defensa) y personales; Rusia acumuló reservas y redujo la exposición al dólar.",
        sources=["Congressional Research Service", "BOFIT"],
    ),
    dict(
        name="Sanciones a Rusia 2022 (invasión de Ucrania)",
        category="sanctions",
        start_date="2022-02-24",
        end_date=None,
        countries=["RU", "UA"],
        variables={
            "type": "comprehensive_financial_tech_oil_cap",
            "multilateral": True,
            "target_behavior": "war",
            "outcome_type": "ongoing",
        },
        outcome="Congelación de ~300.000 M USD de reservas, tope al precio del petróleo, salida de empresas; economía rusa reorientada a China e India y a la guerra.",
        duration_months=None,
        summary="El mayor paquete de sanciones a una gran economía; efecto sobre la capacidad bélica gradual, no inmediato.",
        sources=["KSE Institute", "CREA"],
    ),
    dict(
        name="Sanciones a Sudáfrica (apartheid) 1985-1991",
        category="sanctions",
        start_date="1985-09-01",
        end_date="1991-07-10",
        countries=["ZA"],
        variables={
            "type": "financial_trade_divestment",
            "multilateral": True,
            "target_behavior": "apartheid",
            "outcome_type": "behavior_change_contributing",
        },
        outcome="Contribuyeron (junto a la presión interna y el fin de la Guerra Fría) a la liberación de Mandela (1990) y al fin del apartheid.",
        duration_months=70,
        summary="Ley CAAA de EE. UU. (1986), retirada de crédito bancario (1985) y desinversión empresarial.",
        sources=["Levy (1999)", "Hufbauer et al. (2007) Economic Sanctions Reconsidered"],
    ),
    dict(
        name="Sanciones a Irak 1990-2003",
        category="sanctions",
        start_date="1990-08-06",
        end_date="2003-05-22",
        countries=["IQ"],
        variables={
            "type": "comprehensive_un",
            "multilateral": True,
            "target_behavior": "invasion_wmd",
            "outcome_type": "no_behavior_change_humanitarian_cost",
        },
        outcome="Régimen no cayó por sanciones; grave coste humanitario; programa Petróleo por Alimentos (1996) con corrupción; fin tras la invasión de 2003.",
        duration_months=153,
        summary="Embargo total de la ONU tras la invasión de Kuwait.",
        sources=["ONU, Volcker Committee (2005)"],
    ),
    dict(
        name="Embargo de EE. UU. a Cuba (1960-)",
        category="sanctions",
        start_date="1960-10-19",
        end_date=None,
        countries=["CU", "US"],
        variables={
            "type": "comprehensive_unilateral",
            "multilateral": False,
            "target_behavior": "regime_change",
            "outcome_type": "no_behavior_change",
        },
        outcome="Más de seis décadas sin cambio de régimen; deshielo parcial 2014-2016 revertido; la ONU condena anualmente el embargo.",
        duration_months=None,
        summary="Caso canónico de sanción unilateral prolongada sin lograr su objetivo declarado.",
        sources=["CRS", "Hufbauer et al."],
    ),
    dict(
        name="Sanciones a Libia 1992-2003 (Lockerbie)",
        category="sanctions",
        start_date="1992-03-31",
        end_date="2003-09-12",
        countries=["LY"],
        variables={
            "type": "un_targeted_air_arms",
            "multilateral": True,
            "target_behavior": "terrorism",
            "outcome_type": "negotiated_compliance",
        },
        outcome="Entrega de sospechosos (1999), indemnizaciones y renuncia a ADM (2003); levantamiento de sanciones.",
        duration_months=137,
        summary="Sanciones de la ONU con objetivo acotado y salida negociada.",
        sources=["ONU S/RES/748, 1506"],
    ),
    # ── Golpes de Estado ──
    dict(
        name="Chile 1973",
        category="coup",
        start_date="1973-09-11",
        end_date="1990-03-11",
        countries=["CL"],
        variables={
            "success": True,
            "military": True,
            "foreign_involvement": True,
            "prior_polarization": "high",
            "outcome_regime": "military_dictatorship",
        },
        outcome="Dictadura militar de 17 años; transición pactada tras el plebiscito de 1988.",
        duration_months=198,
        summary="Golpe contra Allende en contexto de hiperinflación, polarización y apoyo encubierto de EE. UU.",
        sources=["Informe Rettig (1991)", "Kornbluh (2003)"],
    ),
    dict(
        name="Turquía 2016: golpe fallido",
        category="coup",
        start_date="2016-07-15",
        end_date="2016-07-16",
        countries=["TR"],
        variables={
            "success": False,
            "military": True,
            "foreign_involvement": False,
            "prior_polarization": "high",
            "outcome_regime": "executive_consolidation",
        },
        outcome="Fracaso en horas; estado de emergencia dos años, purgas masivas y referéndum presidencialista de 2017.",
        duration_months=1,
        summary="Facción militar; movilización civil y lealtad del grueso del ejército lo abortaron.",
        sources=["ICG", "Comisión de Venecia (2017)"],
    ),
    dict(
        name="Egipto 2013",
        category="coup",
        start_date="2013-07-03",
        end_date=None,
        countries=["EG"],
        variables={
            "success": True,
            "military": True,
            "foreign_involvement": False,
            "prior_polarization": "high",
            "outcome_regime": "military_backed_autocracy",
        },
        outcome="Derrocamiento de Morsi tras protestas masivas; Al Sisi presidente desde 2014; represión de la Hermandad.",
        duration_months=None,
        summary="Golpe con apoyo popular parcial un año después de las primeras elecciones libres.",
        sources=["HRW (2014) All According to Plan"],
    ),
    dict(
        name="Myanmar 2021",
        category="coup",
        start_date="2021-02-01",
        end_date=None,
        countries=["MM"],
        variables={
            "success": True,
            "military": True,
            "foreign_involvement": False,
            "prior_polarization": "medium",
            "outcome_regime": "civil_war",
        },
        outcome="Detención de Aung San Suu Kyi, resistencia armada generalizada (PDF) y pérdida de control territorial de la junta desde 2023.",
        duration_months=None,
        summary="El Tatmadaw anula las elecciones de 2020; el golpe desemboca en guerra civil, no en consolidación.",
        sources=["ACLED", "ICG"],
    ),
    dict(
        name="Malí 2020-2021: golpes en cadena",
        category="coup",
        start_date="2020-08-18",
        end_date=None,
        countries=["ML"],
        variables={
            "success": True,
            "military": True,
            "foreign_involvement": True,
            "prior_polarization": "medium",
            "outcome_regime": "military_junta_russia_pivot",
        },
        outcome="Dos golpes en nueve meses, expulsión de Francia y la MINUSMA, llegada de Wagner/Africa Corps, salida de la CEDEAO (2025).",
        duration_months=None,
        summary="Inicio del 'cinturón de golpes' del Sahel (Malí, Burkina Faso, Níger, Guinea).",
        sources=["ICG", "ACLED"],
    ),
    dict(
        name="Níger 2023",
        category="coup",
        start_date="2023-07-26",
        end_date=None,
        countries=["NE"],
        variables={
            "success": True,
            "military": True,
            "foreign_involvement": False,
            "prior_polarization": "low",
            "outcome_regime": "military_junta",
        },
        outcome="La CEDEAO amenazó con intervenir y no lo hizo; sanciones levantadas en 2024; Francia y EE. UU. retiran tropas.",
        duration_months=None,
        summary="Guardia presidencial derroca a Bazoum; consolidación de la Alianza de Estados del Sahel.",
        sources=["ICG"],
    ),
    dict(
        name="España 1981: 23-F",
        category="coup",
        start_date="1981-02-23",
        end_date="1981-02-24",
        countries=["ES"],
        variables={
            "success": False,
            "military": True,
            "foreign_involvement": False,
            "prior_polarization": "high",
            "outcome_regime": "democratic_consolidation",
        },
        outcome="Fracasa en 18 horas; consolida la democracia y el papel de la Corona; condenas en 1982.",
        duration_months=1,
        summary="Asalto al Congreso durante la investidura de Calvo-Sotelo.",
        sources=["Sentencia del Consejo Supremo de Justicia Militar (1982)"],
    ),
    dict(
        name="URSS 1991: golpe de agosto",
        category="coup",
        start_date="1991-08-19",
        end_date="1991-08-21",
        countries=["RU"],
        variables={
            "success": False,
            "military": True,
            "foreign_involvement": False,
            "prior_polarization": "high",
            "outcome_regime": "state_dissolution",
        },
        outcome="Fracasa en tres días, acelera la disolución de la URSS (diciembre 1991).",
        duration_months=1,
        summary="Línea dura del PCUS contra Gorbachov; Yeltsin capitaliza la resistencia.",
        sources=["Plokhy (2014) The Last Empire"],
    ),
    dict(
        name="Bolivia 2019: crisis poselectoral",
        category="coup",
        start_date="2019-11-10",
        end_date="2020-11-08",
        countries=["BO"],
        variables={
            "success": True,
            "military": False,
            "foreign_involvement": False,
            "prior_polarization": "high",
            "outcome_regime": "interim_then_return",
        },
        outcome="Renuncia de Morales tras 'sugerencia' militar; gobierno interino de Áñez; el MAS gana las elecciones de 2020.",
        duration_months=12,
        summary="Caso disputado (golpe frente a vacío de poder): útil para calibrar definiciones.",
        sources=["OEA (2019) informe de auditoría", "Idrobo et al. (2020)"],
    ),
    # ── Revoluciones y levantamientos ──
    dict(
        name="Irán 1979",
        category="revolution",
        start_date="1978-01-01",
        end_date="1979-04-01",
        countries=["IR"],
        variables={
            "success": True,
            "violence": "medium",
            "regime_type_before": "monarchy",
            "outcome_regime": "theocracy",
            "military_defection": True,
        },
        outcome="Caída del sha, República Islámica, crisis de los rehenes y guerra con Irak (1980-88).",
        duration_months=15,
        summary="Coalición amplia (clero, bazar, izquierda) contra la monarquía; el clero captura el resultado.",
        sources=["Kurzman (2004) The Unthinkable Revolution"],
    ),
    dict(
        name="Túnez 2011",
        category="revolution",
        start_date="2010-12-17",
        end_date="2011-01-14",
        countries=["TN"],
        variables={
            "success": True,
            "violence": "low",
            "regime_type_before": "autocracy",
            "outcome_regime": "democracy_then_backsliding",
            "military_defection": True,
        },
        outcome="Huida de Ben Ali en 28 días; única democracia de la Primavera Árabe hasta el autogolpe de Saied (2021).",
        duration_months=1,
        summary="Inmolación de Bouazizi; el ejército se niega a disparar.",
        sources=["ICG", "V-Dem"],
    ),
    dict(
        name="Egipto 2011",
        category="revolution",
        start_date="2011-01-25",
        end_date="2011-02-11",
        countries=["EG"],
        variables={
            "success": True,
            "violence": "medium",
            "regime_type_before": "autocracy",
            "outcome_regime": "military_tutelage",
            "military_defection": True,
        },
        outcome="Caída de Mubarak en 18 días; elecciones (2012) y golpe (2013): la revolución no cambia el Estado profundo.",
        duration_months=1,
        summary="Protestas masivas en Tahrir; el ejército retira su apoyo al presidente.",
        sources=["Kandil (2012) Soldiers, Spies and Statesmen"],
    ),
    dict(
        name="Ucrania 2013-2014: Euromaidán",
        category="revolution",
        start_date="2013-11-21",
        end_date="2014-02-22",
        countries=["UA"],
        variables={
            "success": True,
            "violence": "medium",
            "regime_type_before": "hybrid",
            "outcome_regime": "pro_western_democracy",
            "military_defection": True,
        },
        outcome="Huida de Yanukóvich; anexión rusa de Crimea y guerra en el Donbás como reacción.",
        duration_months=3,
        summary="Protestas por el acuerdo de asociación con la UE; represión letal en febrero precipita el desenlace.",
        sources=["Wilson (2014) Ukraine Crisis"],
    ),
    dict(
        name="Europa del Este 1989",
        category="revolution",
        start_date="1989-06-04",
        end_date="1989-12-29",
        countries=["PL", "HU", "DE", "CZ", "RO"],
        variables={
            "success": True,
            "violence": "low",
            "regime_type_before": "communist",
            "outcome_regime": "democracy",
            "military_defection": True,
        },
        outcome="Caída en cascada de los regímenes comunistas en siete meses; violencia solo en Rumanía.",
        duration_months=7,
        summary="Retirada de la garantía soviética (doctrina Sinatra) y cascada de revelación de preferencias.",
        sources=["Kuran (1991) Now Out of Never"],
    ),
    dict(
        name="Bielorrusia 2020: protestas fallidas",
        category="revolution",
        start_date="2020-08-09",
        end_date="2021-03-01",
        countries=["BY"],
        variables={
            "success": False,
            "violence": "medium",
            "regime_type_before": "autocracy",
            "outcome_regime": "hardened_autocracy",
            "military_defection": False,
        },
        outcome="Represión, exilio de la oposición, dependencia total de Rusia.",
        duration_months=7,
        summary="Fraude electoral y protestas masivas sin defección de las fuerzas de seguridad.",
        sources=["Viasna", "OSCE Moscow Mechanism (2020)"],
    ),
    dict(
        name="Hong Kong 2019",
        category="revolution",
        start_date="2019-06-09",
        end_date="2020-06-30",
        countries=["CN"],
        variables={
            "success": False,
            "violence": "medium",
            "regime_type_before": "hybrid_special_region",
            "outcome_regime": "authoritarian_integration",
            "military_defection": False,
        },
        outcome="Ley de Seguridad Nacional (2020), fin de la oposición política y de la prensa independiente.",
        duration_months=13,
        summary="Movimiento contra la ley de extradición; Pekín responde con integración autoritaria.",
        sources=["HRW", "Hong Kong Watch"],
    ),
    dict(
        name="Sudán 2019",
        category="revolution",
        start_date="2018-12-19",
        end_date="2019-08-17",
        countries=["SD"],
        variables={
            "success": True,
            "violence": "medium",
            "regime_type_before": "autocracy",
            "outcome_regime": "transition_then_coup_then_war",
            "military_defection": True,
        },
        outcome="Caída de al-Bashir, transición cívico-militar, golpe (2021) y guerra entre ejército y RSF (2023).",
        duration_months=8,
        summary="Protestas por el pan; el ejército depone al dictador y luego captura la transición.",
        sources=["ICG", "ACLED"],
    ),
    dict(
        name="Chile 2019: estallido social",
        category="revolution",
        start_date="2019-10-18",
        end_date="2022-09-04",
        countries=["CL"],
        variables={
            "success": False,
            "violence": "medium",
            "regime_type_before": "democracy",
            "outcome_regime": "constitutional_process_rejected",
            "military_defection": False,
        },
        outcome="Proceso constituyente; la propuesta es rechazada en 2022 (62%) y una segunda en 2023.",
        duration_months=35,
        summary="Protesta por el precio del metro que escala a demanda de nueva constitución.",
        sources=["Servel", "PNUD (2020)"],
    ),
    # ── Pandemias ──
    dict(
        name="Gripe de 1918",
        category="pandemic",
        start_date="1918-03-01",
        end_date="1920-04-01",
        countries=["US", "ES", "IN"],
        variables={
            "pathogen": "influenza_H1N1",
            "cfr": "~2,5%",
            "npi": True,
            "vaccine": False,
            "gdp_impact": "−6% (est.)",
        },
        outcome="50-100 millones de muertes; ciudades con intervenciones tempranas tuvieron menor mortalidad y mejor recuperación económica.",
        duration_months=25,
        summary="Tres olas; el nombre 'española' proviene de la censura de prensa en los beligerantes.",
        sources=["Barro et al. (2020) NBER", "Correia, Luck & Verner (2020)"],
    ),
    dict(
        name="SARS 2003",
        category="pandemic",
        start_date="2002-11-16",
        end_date="2003-07-05",
        countries=["CN", "SG", "CA"],
        variables={
            "pathogen": "SARS-CoV-1",
            "cfr": "~10%",
            "npi": True,
            "vaccine": False,
            "gdp_impact": "−1 pp Asia oriental",
        },
        outcome="8.096 casos, 774 muertes; contenido por aislamiento y rastreo; reforma del Reglamento Sanitario Internacional (2005).",
        duration_months=8,
        summary="Ocultación inicial china; contención exitosa por baja transmisión presintomática.",
        sources=["OMS"],
    ),
    dict(
        name="Ébola en África occidental 2014-2016",
        category="pandemic",
        start_date="2013-12-01",
        end_date="2016-06-09",
        countries=["GN", "SL", "LR"],
        variables={
            "pathogen": "Ebola_Zaire",
            "cfr": "~40%",
            "npi": True,
            "vaccine": True,
            "gdp_impact": "−2,8 mil M USD",
        },
        outcome="28.600 casos y 11.325 muertes; PHEIC de la OMS; vacuna rVSV-ZEBOV probada en anillo (2015).",
        duration_months=30,
        summary="Respuesta internacional tardía; MSF alertó meses antes de la declaración de emergencia.",
        sources=["OMS", "Banco Mundial"],
    ),
    dict(
        name="COVID-19",
        category="pandemic",
        start_date="2019-12-01",
        end_date="2023-05-05",
        countries=["CN", "US", "IT", "ES"],
        variables={
            "pathogen": "SARS-CoV-2",
            "cfr": "~1% (IFR <1%)",
            "npi": True,
            "vaccine": True,
            "gdp_impact": "−3,1% mundial (2020)",
        },
        outcome="≈7 millones de muertes confirmadas (exceso de mortalidad ~15-20 M); vacunas en 11 meses; fin de la PHEIC en mayo de 2023.",
        duration_months=41,
        summary="Confinamientos, estímulo fiscal y monetario sin precedentes, inflación posterior y reordenación de cadenas de suministro.",
        sources=["OMS", "The Economist excess deaths model", "FMI WEO"],
    ),
    dict(
        name="Mpox 2022",
        category="pandemic",
        start_date="2022-05-01",
        end_date="2023-05-11",
        countries=["ES", "US", "BR"],
        variables={
            "pathogen": "MPXV_clade_IIb",
            "cfr": "<0,2%",
            "npi": False,
            "vaccine": True,
            "gdp_impact": "insignificante",
        },
        outcome="~87.000 casos; PHEIC; contenido por vacunación dirigida y cambio de conducta; nueva PHEIC por clado Ib en 2024.",
        duration_months=12,
        summary="Brote fuera de África concentrado en redes sexuales; respuesta rápida en comparación con la COVID-19.",
        sources=["OMS", "ECDC"],
    ),
    # ── Referendos de secesión y salida ──
    dict(
        name="Quebec 1995",
        category="secession_referendum",
        start_date="1995-10-30",
        end_date="1995-10-30",
        countries=["CA"],
        variables={"legal": True, "result_yes": "49,4%", "recognized": True, "outcome_type": "remain"},
        outcome="No gana por 54.000 votos; Ley de Claridad (2000) fija condiciones para futuros referendos.",
        duration_months=1,
        summary="Segundo referendo tras 1980; caso de referencia sobre secesión legal en democracias.",
        sources=["Tribunal Supremo de Canadá, Reference re Secession of Quebec (1998)"],
    ),
    dict(
        name="Escocia 2014",
        category="secession_referendum",
        start_date="2014-09-18",
        end_date="2014-09-18",
        countries=["GB"],
        variables={"legal": True, "result_yes": "44,7%", "recognized": True, "outcome_type": "remain"},
        outcome="No gana (55,3%); el Brexit reabre la cuestión; el Tribunal Supremo niega competencia a Holyrood para convocar otro (2022).",
        duration_months=1,
        summary="Referendo pactado (Acuerdo de Edimburgo) con participación del 84,6%.",
        sources=["Electoral Commission UK"],
    ),
    dict(
        name="Cataluña 2017",
        category="secession_referendum",
        start_date="2017-10-01",
        end_date="2017-10-27",
        countries=["ES"],
        variables={
            "legal": False,
            "result_yes": "90% (participación 43%)",
            "recognized": False,
            "outcome_type": "suspended_autonomy",
        },
        outcome="Declaración unilateral, artículo 155, condenas por sedición (2019), indultos (2021) y amnistía (2024).",
        duration_months=1,
        summary="Referendo suspendido por el TC y celebrado sin garantías; ningún Estado reconoció la declaración.",
        sources=["STC 114/2017", "STS 459/2019"],
    ),
    dict(
        name="Sudán del Sur 2011",
        category="secession_referendum",
        start_date="2011-01-09",
        end_date="2011-07-09",
        countries=["SS", "SD"],
        variables={
            "legal": True,
            "result_yes": "98,8%",
            "recognized": True,
            "outcome_type": "independence_then_civil_war",
        },
        outcome="Independencia reconocida; guerra civil desde 2013 (~400.000 muertos).",
        duration_months=6,
        summary="Referendo pactado en el CPA de 2005; la independencia no resolvió el conflicto interno.",
        sources=["ONU", "Checchi et al. (2018) LSHTM"],
    ),
    dict(
        name="Brexit 2016",
        category="secession_referendum",
        start_date="2016-06-23",
        end_date="2020-12-31",
        countries=["GB"],
        variables={
            "legal": True,
            "result_yes": "51,9%",
            "recognized": True,
            "outcome_type": "exit_completed",
        },
        outcome="Salida de la UE (31-1-2020) y del mercado único (31-12-2020); PIB ~4% menor a largo plazo según la OBR.",
        duration_months=54,
        summary="Referendo consultivo con margen estrecho; tres primeros ministros hasta cerrar la salida.",
        sources=["OBR (2023)", "House of Commons Library"],
    ),
    dict(
        name="Kurdistán iraquí 2017",
        category="secession_referendum",
        start_date="2017-09-25",
        end_date="2017-10-16",
        countries=["IQ"],
        variables={
            "legal": False,
            "result_yes": "92,7%",
            "recognized": False,
            "outcome_type": "military_reversal",
        },
        outcome="Bagdad retoma Kirkuk en tres semanas; el Gobierno regional pierde territorio e ingresos.",
        duration_months=1,
        summary="Referendo unilateral sin apoyo internacional; represalia militar y económica del Estado central.",
        sources=["ICG (2017)"],
    ),
    dict(
        name="Montenegro 2006",
        category="secession_referendum",
        start_date="2006-05-21",
        end_date="2006-06-03",
        countries=["ME", "RS"],
        variables={
            "legal": True,
            "result_yes": "55,5% (umbral UE 55%)",
            "recognized": True,
            "outcome_type": "independence",
        },
        outcome="Independencia pacífica reconocida por Serbia y la UE.",
        duration_months=1,
        summary="Umbral de mayoría cualificada negociado con la UE.",
        sources=["OSCE/ODIHR (2006)"],
    ),
    # ── Transiciones de hegemonía, alianzas, sistema monetario ──
    dict(
        name="Suez 1956",
        category="hegemonic_transition",
        start_date="1956-10-29",
        end_date="1957-03-01",
        countries=["GB", "FR", "EG", "US"],
        variables={
            "trigger": "canal_nationalization",
            "hegemon_action": "financial_coercion",
            "outcome_type": "power_transfer_confirmed",
        },
        outcome="EE. UU. fuerza la retirada anglo-francesa con presión sobre la libra; fin del papel de Reino Unido como potencia independiente.",
        duration_months=5,
        summary="Nacionalización del canal por Nasser; intervención militar sin respaldo estadounidense.",
        sources=["Kunz (1991) The Economic Diplomacy of the Suez Crisis"],
    ),
    dict(
        name="Fin de Bretton Woods 1971",
        category="monetary_regime_change",
        start_date="1971-08-15",
        end_date="1973-03-01",
        countries=["US"],
        variables={"trigger": "dollar_overvaluation_gold_drain", "outcome_type": "float"},
        outcome="Nixon suspende la convertibilidad en oro; Smithsonian (1971) fracasa; flotación generalizada desde 1973.",
        duration_months=19,
        summary="Dilema de Triffin y financiación de Vietnam y la Gran Sociedad.",
        sources=["Eichengreen (2011) Exorbitant Privilege"],
    ),
    dict(
        name="Disolución del Pacto de Varsovia 1991",
        category="alliance_collapse",
        start_date="1991-02-25",
        end_date="1991-07-01",
        countries=["RU", "PL", "HU", "CZ"],
        variables={"trigger": "regime_change_members", "outcome_type": "dissolution"},
        outcome="Disolución formal; expansión de la OTAN al este desde 1999.",
        duration_months=5,
        summary="Las alianzas de hegemón único no sobreviven a la pérdida de coerción del hegemón.",
        sources=["Mastny & Byrne (2005)"],
    ),
    dict(
        name="Ruptura chino-soviética 1960-1969",
        category="alliance_collapse",
        start_date="1960-07-01",
        end_date="1969-03-02",
        countries=["CN", "RU"],
        variables={"trigger": "ideological_and_leadership_rivalry", "outcome_type": "armed_border_clash"},
        outcome="Retirada de técnicos soviéticos (1960), choques en el Ussuri (1969), apertura de China a EE. UU. (1972).",
        duration_months=104,
        summary="Ejemplo de alianza ideológica que se rompe por rivalidad de liderazgo y seguridad.",
        sources=["Lüthi (2008) The Sino-Soviet Split"],
    ),
    dict(
        name="Acuerdo del Plaza 1985",
        category="monetary_regime_change",
        start_date="1985-09-22",
        end_date="1987-02-22",
        countries=["US", "JP", "DE", "FR", "GB"],
        variables={"trigger": "dollar_overvaluation", "outcome_type": "coordinated_depreciation"},
        outcome="Dólar −40% frente al yen y el marco; Acuerdo del Louvre (1987) frena la caída.",
        duration_months=17,
        summary="Coordinación cambiaria del G5; precedente de los debates actuales sobre 'acuerdos' cambiarios.",
        sources=["Funabashi (1988) Managing the Dollar"],
    ),
    # ── Altos el fuego y acuerdos de paz ──
    dict(
        name="Minsk II 2015",
        category="ceasefire",
        start_date="2015-02-12",
        end_date="2022-02-24",
        countries=["UA", "RU"],
        variables={
            "third_party_guarantor": True,
            "monitoring": "OSCE",
            "political_settlement": False,
            "outcome_type": "collapsed",
        },
        outcome="Violaciones continuas; nunca se aplicó el componente político; la invasión de 2022 lo entierra.",
        duration_months=84,
        summary="Alto el fuego sin acuerdo sobre secuencia (elecciones frente a control fronterizo).",
        sources=["OSCE SMM", "ICG"],
    ),
    dict(
        name="Dayton 1995",
        category="ceasefire",
        start_date="1995-12-14",
        end_date=None,
        countries=["BA", "RS", "HR"],
        variables={
            "third_party_guarantor": True,
            "monitoring": "NATO_IFOR_SFOR_EUFOR",
            "political_settlement": True,
            "outcome_type": "held_frozen",
        },
        outcome="Sin retorno a la guerra en 30 años; Estado disfuncional con amenazas secesionistas de la República Srpska.",
        duration_months=None,
        summary="Paz impuesta con fuerza multinacional y constitución consociativa.",
        sources=["OHR", "ICG"],
    ),
    dict(
        name="Acuerdo de Viernes Santo 1998",
        category="ceasefire",
        start_date="1998-04-10",
        end_date=None,
        countries=["GB", "IE"],
        variables={
            "third_party_guarantor": True,
            "monitoring": "IICD",
            "political_settlement": True,
            "outcome_type": "held",
        },
        outcome="Fin de la violencia a gran escala; desarme del IRA (2005); tensiones renovadas por el Brexit (Protocolo/Marco de Windsor).",
        duration_months=None,
        summary="Referendos simultáneos, poder compartido y dimensión transfronteriza.",
        sources=["Gobiernos de Reino Unido e Irlanda"],
    ),
    dict(
        name="Armisticio de Corea 1953",
        category="ceasefire",
        start_date="1953-07-27",
        end_date=None,
        countries=["KR", "KP", "US", "CN"],
        variables={
            "third_party_guarantor": True,
            "monitoring": "UNC_MAC",
            "political_settlement": False,
            "outcome_type": "held_no_treaty",
        },
        outcome="Sin tratado de paz 70 años después; frontera militarizada; ejemplo de conflicto congelado estable.",
        duration_months=None,
        summary="Alto el fuego militar sin acuerdo político; disuasión sostiene la paz.",
        sources=["UNC"],
    ),
    dict(
        name="Alto el fuego de Nagorno-Karabaj 1994",
        category="ceasefire",
        start_date="1994-05-12",
        end_date="2020-09-27",
        countries=["AM", "AZ"],
        variables={
            "third_party_guarantor": True,
            "monitoring": "OSCE_Minsk_Group",
            "political_settlement": False,
            "outcome_type": "collapsed",
        },
        outcome="26 años congelado; guerra de 2020 y ofensiva de 2023 acaban con la entidad armenia y provocan el éxodo de 100.000 personas.",
        duration_months=316,
        summary="Conflicto congelado sin acuerdo político; el desequilibrio militar creciente lo rompió.",
        sources=["ICG", "OSCE"],
    ),
    dict(
        name="Acuerdo de paz de Colombia 2016 (FARC)",
        category="ceasefire",
        start_date="2016-11-24",
        end_date=None,
        countries=["CO"],
        variables={
            "third_party_guarantor": True,
            "monitoring": "UN_Verification_Mission",
            "political_settlement": True,
            "outcome_type": "held_partially",
        },
        outcome="Desarme de ~13.000 combatientes; disidencias y violencia contra líderes sociales persisten; plebiscito perdido (2016) y acuerdo revisado por el Congreso.",
        duration_months=None,
        summary="Justicia transicional (JEP) y participación política; implementación desigual.",
        sources=["Instituto Kroc (informes de implementación)"],
    ),
    dict(
        name="Oslo 1993",
        category="ceasefire",
        start_date="1993-09-13",
        end_date="2000-09-28",
        countries=["IL", "PS"],
        variables={
            "third_party_guarantor": True,
            "monitoring": "none_formal",
            "political_settlement": False,
            "outcome_type": "collapsed",
        },
        outcome="Autonomía palestina limitada; asesinato de Rabin (1995), Camp David fracasa y estalla la Segunda Intifada (2000).",
        duration_months=84,
        summary="Acuerdo marco que pospuso las cuestiones finales (Jerusalén, refugiados, fronteras).",
        sources=["Shlaim (2000) The Iron Wall"],
    ),
    # ── Bancos centrales y shocks financieros ──
    dict(
        name="Shock Volcker 1979-1982",
        category="monetary_shock",
        start_date="1979-10-06",
        end_date="1982-08-01",
        countries=["US"],
        variables={
            "policy": "rate_hike_to_20%",
            "inflation_start": "13%",
            "recession": True,
            "outcome_type": "disinflation_success",
        },
        outcome="Inflación del 13% al 3% (1983) a costa de dos recesiones y paro del 10,8%.",
        duration_months=34,
        summary="Credibilidad antiinflacionaria como bien público; referencia para 2022.",
        sources=["Goodfriend & King (2005)"],
    ),
    dict(
        name="Miércoles negro 1992 (libra fuera del SME)",
        category="monetary_shock",
        start_date="1992-09-16",
        end_date="1992-09-16",
        countries=["GB"],
        variables={
            "policy": "defend_peg_fail",
            "inflation_start": "4%",
            "recession": True,
            "outcome_type": "peg_abandoned_then_recovery",
        },
        outcome="Salida del SME, devaluación ~15%, recuperación económica y adopción de objetivos de inflación.",
        duration_months=1,
        summary="Ataque especulativo contra una paridad inconsistente con la política interna.",
        sources=["Banco de Inglaterra"],
    ),
    dict(
        name="BCE 2011: subidas de tipos revertidas",
        category="monetary_shock",
        start_date="2011-04-07",
        end_date="2011-11-03",
        countries=["EU"],
        variables={
            "policy": "two_hikes_then_cut",
            "inflation_start": "2,7%",
            "recession": True,
            "outcome_type": "policy_error_reversed",
        },
        outcome="Dos subidas (abril y julio) en plena crisis soberana; Draghi las revierte en noviembre y diciembre.",
        duration_months=7,
        summary="Ejemplo de reacción a inflación de oferta (energía) con demanda débil.",
        sources=["BCE, decisiones de política monetaria 2011"],
    ),
    dict(
        name="SNB 2015: fin del suelo del franco",
        category="monetary_shock",
        start_date="2015-01-15",
        end_date="2015-01-15",
        countries=["CH"],
        variables={"policy": "abandon_floor", "outcome_type": "abrupt_appreciation"},
        outcome="Franco +30% intradía frente al euro, pérdidas en brókers y bancos; tipos negativos hasta 2022.",
        duration_months=1,
        summary="Un banco central abandona por sorpresa un compromiso 'ilimitado'.",
        sources=["SNB"],
    ),
    dict(
        name="Ciclo de endurecimiento global 2022-2023",
        category="monetary_shock",
        start_date="2022-03-16",
        end_date="2023-09-14",
        countries=["US", "EU", "GB"],
        variables={
            "policy": "fastest_hikes_since_1980s",
            "inflation_start": "8-10%",
            "recession": False,
            "outcome_type": "soft_landing_so_far",
        },
        outcome="Fed 0-5,5%, BCE −0,5-4%; inflación de vuelta a ~2-3% sin recesión en EE. UU.; quiebra de SVB y Credit Suisse (2023).",
        duration_months=18,
        summary="Inflación pospandemia y energética; debate sobre transitoriedad.",
        sources=["Fed", "BCE", "BIS Annual Report 2023"],
    ),
    dict(
        name="Japón 1990: estallido de la burbuja",
        category="monetary_shock",
        start_date="1990-01-01",
        end_date="2003-12-31",
        countries=["JP"],
        variables={"policy": "late_hikes_then_zero_rates", "outcome_type": "lost_decades_deflation"},
        outcome="Nikkei −80% hasta 2003, deflación, deuda pública >200% del PIB; el Nikkei no recupera 1989 hasta 2024.",
        duration_months=168,
        summary="Burbuja inmobiliaria y bursátil tras el Plaza; bancos zombis y respuesta fiscal-monetaria tardía.",
        sources=["Koo (2008) The Holy Grail of Macroeconomics"],
    ),
    dict(
        name="Crisis financiera global 2008",
        category="monetary_shock",
        start_date="2007-08-09",
        end_date="2009-06-30",
        countries=["US", "GB", "EU"],
        variables={
            "policy": "zero_rates_QE_bailouts",
            "recession": True,
            "outcome_type": "deep_recession_slow_recovery",
        },
        outcome="Quiebra de Lehman (sept. 2008), PIB mundial −0,1% (2009), QE y regulación (Basilea III, Dodd-Frank).",
        duration_months=23,
        summary="Hipotecas subprime, titulización opaca y apalancamiento bancario.",
        sources=["FCIC (2011)", "Bernanke (2015) The Courage to Act"],
    ),
    # ── Shocks energéticos ──
    dict(
        name="Embargo petrolero de 1973",
        category="energy_shock",
        start_date="1973-10-17",
        end_date="1974-03-18",
        countries=["SA", "US", "NL"],
        variables={
            "trigger": "war_yom_kippur",
            "price_change": "×4",
            "outcome_type": "stagflation_policy_shift",
        },
        outcome="Precio del crudo de 3 a 12 USD; estanflación; creación de la AIE (1974) y reservas estratégicas.",
        duration_months=5,
        summary="Uso del petróleo como arma política por la OPEP árabe.",
        sources=["Yergin (1991) The Prize"],
    ),
    dict(
        name="Segunda crisis del petróleo 1979",
        category="energy_shock",
        start_date="1979-01-01",
        end_date="1981-12-31",
        countries=["IR", "US"],
        variables={
            "trigger": "iranian_revolution_iran_iraq_war",
            "price_change": "×2,5",
            "outcome_type": "recession_demand_destruction",
        },
        outcome="Crudo hasta ~40 USD; recesión 1980-82; caída de la demanda y contra-shock de 1986.",
        duration_months=36,
        summary="Pánico de inventarios más que caída física de la oferta.",
        sources=["Hamilton (2011) Historical Oil Shocks"],
    ),
    dict(
        name="Crisis del gas en Europa 2022",
        category="energy_shock",
        start_date="2022-02-24",
        end_date="2023-03-31",
        countries=["EU", "DE", "RU"],
        variables={
            "trigger": "russia_supply_cut",
            "price_change": "TTF ×10 (pico 340 €/MWh)",
            "outcome_type": "demand_reduction_diversification",
        },
        outcome="Gas ruso por gasoducto del 40% al <10% del suministro europeo; GNL, ahorro del 15% y precios de vuelta a ~30-50 €/MWh en 2023.",
        duration_months=13,
        summary="Arma energética rusa; Europa evita el racionamiento con demanda, GNL y un invierno suave.",
        sources=["AIE", "Bruegel European natural gas imports dataset"],
    ),
    dict(
        name="Petróleo negativo, abril de 2020",
        category="energy_shock",
        start_date="2020-04-20",
        end_date="2020-04-21",
        countries=["US"],
        variables={
            "trigger": "pandemic_demand_collapse_storage_full",
            "price_change": "WTI −37 USD",
            "outcome_type": "opec_plus_cuts",
        },
        outcome="Precio negativo por saturación de almacenamiento en Cushing; recorte histórico de la OPEP+ (9,7 mb/d).",
        duration_months=1,
        summary="Anomalía de mercado físico; útil para explicar contango y límites de almacenamiento.",
        sources=["CME", "AIE Oil Market Report mayo 2020"],
    ),
    dict(
        name="Invasión de Kuwait 1990",
        category="energy_shock",
        start_date="1990-08-02",
        end_date="1991-02-28",
        countries=["IQ", "KW", "US"],
        variables={
            "trigger": "invasion_producer",
            "price_change": "×2 (17→36 USD)",
            "outcome_type": "coalition_war_price_normalization",
        },
        outcome="Pico del crudo en octubre de 1990; la victoria de la coalición normaliza precios en semanas; recesión leve en EE. UU.",
        duration_months=7,
        summary="Estudio de evento clásico para reacción del petróleo a conflicto en el Golfo.",
        sources=["Hamilton (2011)"],
    ),
]

# ── Mapa argumental semilla: Renta Básica Universal ──
RBU_MAP = {
    "title": "Renta básica universal: ¿justa y viable?",
    "topic": "Renta básica universal",
    "nodes": [
        {
            "key": "T",
            "kind": "thesis",
            "text": "Una renta básica universal e incondicional es justa y viable en una economía avanzada.",
            "author": None,
            "work": None,
            "x": 400,
            "y": 40,
        },
        {
            "key": "P1",
            "kind": "premise",
            "text": "La libertad real exige medios, no solo ausencia de interferencia: la RBU maximiza la libertad real del que menos tiene.",
            "author": "Philippe Van Parijs",
            "work": "Real Freedom for All (1995)",
            "x": 120,
            "y": 180,
        },
        {
            "key": "P2",
            "kind": "premise",
            "text": "Gran parte de la riqueza actual es herencia común (tierra, tecnología, instituciones): un dividendo social es la devolución de lo común.",
            "author": "Thomas Paine",
            "work": "Agrarian Justice (1797)",
            "x": 400,
            "y": 180,
        },
        {
            "key": "P3",
            "kind": "premise",
            "text": "Un suelo mínimo garantizado es compatible con una sociedad libre y de mercado.",
            "author": "Friedrich Hayek",
            "work": "Los fundamentos de la libertad (1960), cap. 19; Law, Legislation and Liberty III (1979)",
            "x": 680,
            "y": 180,
        },
        {
            "key": "O1",
            "kind": "objection",
            "text": "Objeción de reciprocidad: quien puede contribuir y elige no hacerlo vive del trabajo de los demás; una renta incondicional viola la justicia como cooperación equitativa.",
            "author": "Usuario (inspirada en Stuart White, The Civic Minimum, 2003)",
            "work": None,
            "is_user": True,
            "x": 120,
            "y": 330,
        },
        {
            "key": "R1",
            "kind": "reply",
            "text": "Los empleos son un activo escaso repartido injustamente: quien lo ocupa recibe una renta de escasez; la RBU se financia con esa renta, no con el esfuerzo ajeno (el 'surfista de Malibú' no explota a nadie).",
            "author": "Philippe Van Parijs",
            "work": "Why Surfers Should Be Fed (1991)",
            "x": 120,
            "y": 480,
        },
        {
            "key": "O2",
            "kind": "objection",
            "text": "Alternativa: renta de participación condicionada a una contribución social amplia (empleo, cuidados, formación, voluntariado).",
            "author": "Anthony Atkinson",
            "work": "The Case for a Participation Income (1996); Inequality (2015)",
            "x": 400,
            "y": 330,
        },
        {
            "key": "O3",
            "kind": "objection",
            "text": "Rawls incluye el ocio entre los bienes primarios: quien elige no trabajar no puede reclamar el principio de diferencia.",
            "author": "John Rawls",
            "work": "The Priority of Right and Ideas of the Good (1988), n. 7; Justice as Fairness (2001)",
            "x": 680,
            "y": 330,
        },
        {
            "key": "O4",
            "kind": "objection",
            "text": "Coste fiscal y oferta de trabajo: una RBU suficiente exige tipos impositivos muy altos y podría reducir horas trabajadas.",
            "author": None,
            "work": "Experimentos de impuesto negativo en EE. UU. (1968-1980)",
            "x": 960,
            "y": 330,
        },
        {
            "key": "E1",
            "kind": "evidence",
            "text": "Finlandia 2017-2018 (Kela, 2.000 parados): sin efecto significativo en empleo el primer año, ligero aumento el segundo; mejora de bienestar y confianza.",
            "author": "Kela",
            "work": "Informe final del experimento (2020)",
            "x": 40,
            "y": 620,
        },
        {
            "key": "E2",
            "kind": "evidence",
            "text": "Kenia (GiveDirectly): transferencias universales en aldeas aumentan consumo, activos y actividad empresarial; sin caída de la oferta laboral; efectos multiplicadores locales.",
            "author": "Egger, Haushofer, Miguel, Niehaus, Walker",
            "work": "General Equilibrium Effects of Cash Transfers, Econometrica (2022)",
            "x": 300,
            "y": 620,
        },
        {
            "key": "E3",
            "kind": "evidence",
            "text": "Stockton SEED (2019-2021, 500 USD/mes): el empleo a tiempo completo subió más en el grupo tratado (del 28% al 40%) que en el control.",
            "author": "West, Castro Baker et al.",
            "work": "Preliminary Analysis: SEED (2021)",
            "x": 560,
            "y": 620,
        },
        {
            "key": "E4",
            "kind": "evidence",
            "text": "Alaska Permanent Fund Dividend: sin efecto en el empleo total; aumento del trabajo a tiempo parcial.",
            "author": "Jones & Marinescu",
            "work": "The Labor Market Impacts of Universal and Permanent Cash Transfers, AEJ: Policy (2022)",
            "x": 820,
            "y": 620,
        },
        {
            "key": "E5",
            "kind": "evidence",
            "text": "Experimentos de impuesto negativo (Nueva Jersey, Seattle-Denver): reducción modesta de horas (mayor en segundos perceptores), no abandono del empleo.",
            "author": "Robins",
            "work": "A Comparison of the Labor Supply Findings from the Four NIT Experiments, JHR (1985)",
            "x": 1080,
            "y": 620,
        },
    ],
    "edges": [
        ("P1", "T", "supports"),
        ("P2", "T", "supports"),
        ("P3", "T", "supports"),
        ("O1", "T", "attacks"),
        ("R1", "O1", "replies"),
        ("O2", "T", "attacks"),
        ("O3", "P1", "attacks"),
        ("O4", "T", "attacks"),
        ("E1", "O4", "attacks"),
        ("E2", "T", "supports"),
        ("E3", "O4", "attacks"),
        ("E4", "O4", "attacks"),
        ("E5", "O4", "supports"),
    ],
}

# ── Genealogía de la libertad (grafo de conceptos e influencias) ──
GENEALOGY_LIBERTY = {
    "title": "Genealogía del concepto de libertad",
    "nodes": [
        {
            "id": "maquiavelo",
            "label": "Maquiavelo",
            "years": "1469-1527",
            "work": "Discursos sobre la primera década de Tito Livio (1531)",
            "concept": "libertad republicana: vivere libero, no dominación por el conflicto ordenado",
        },
        {
            "id": "hobbes",
            "label": "Hobbes",
            "years": "1588-1679",
            "work": "Leviatán (1651), cap. XXI",
            "concept": "libertad como ausencia de impedimentos externos al movimiento",
        },
        {
            "id": "locke",
            "label": "Locke",
            "years": "1632-1704",
            "work": "Segundo tratado sobre el gobierno civil (1689)",
            "concept": "libertad bajo la ley natural; consentimiento y propiedad",
        },
        {
            "id": "montesquieu",
            "label": "Montesquieu",
            "years": "1689-1755",
            "work": "El espíritu de las leyes (1748), XI",
            "concept": "libertad política como seguridad; separación de poderes",
        },
        {
            "id": "rousseau",
            "label": "Rousseau",
            "years": "1712-1778",
            "work": "El contrato social (1762)",
            "concept": "libertad como obediencia a la ley que uno se ha dado (autonomía colectiva)",
        },
        {
            "id": "kant",
            "label": "Kant",
            "years": "1724-1804",
            "work": "Fundamentación (1785); La paz perpetua (1795)",
            "concept": "autonomía moral; libertad como independencia de la coacción ajena compatible con la de todos",
        },
        {
            "id": "constant",
            "label": "Constant",
            "years": "1767-1830",
            "work": "De la libertad de los antiguos comparada con la de los modernos (1819)",
            "concept": "libertad de los modernos (privada) frente a la de los antiguos (participación)",
        },
        {
            "id": "mill",
            "label": "J. S. Mill",
            "years": "1806-1873",
            "work": "Sobre la libertad (1859)",
            "concept": "principio del daño; tiranía de la mayoría",
        },
        {
            "id": "berlin",
            "label": "Isaiah Berlin",
            "years": "1909-1997",
            "work": "Dos conceptos de libertad (1958)",
            "concept": "libertad negativa frente a libertad positiva",
        },
        {
            "id": "hayek",
            "label": "Hayek",
            "years": "1899-1992",
            "work": "Los fundamentos de la libertad (1960)",
            "concept": "libertad como ausencia de coacción arbitraria; Estado de derecho",
        },
        {
            "id": "rawls",
            "label": "Rawls",
            "years": "1921-2002",
            "work": "Teoría de la justicia (1971)",
            "concept": "libertades básicas iguales y su valor equitativo",
        },
        {
            "id": "pettit",
            "label": "Pettit",
            "years": "1945-",
            "work": "Republicanismo (1997); De la República a la Democracia (2012)",
            "concept": "libertad como no dominación",
        },
        {
            "id": "skinner",
            "label": "Skinner",
            "years": "1940-",
            "work": "Liberty before Liberalism (1998)",
            "concept": "libertad neorromana; recuperación histórica del republicanismo",
        },
        {
            "id": "sen",
            "label": "Amartya Sen",
            "years": "1933-",
            "work": "Desarrollo y libertad (1999)",
            "concept": "libertad como capacidad efectiva",
        },
        {
            "id": "strauss",
            "label": "Leo Strauss",
            "years": "1899-1973",
            "work": "¿Qué es filosofía política? (1959)",
            "concept": "crítica del historicismo y del positivismo; retorno a los clásicos",
        },
    ],
    "edges": [
        ("hobbes", "locke", "reacción"),
        ("locke", "montesquieu", "influencia"),
        ("locke", "kant", "influencia"),
        ("rousseau", "kant", "influencia"),
        ("hobbes", "constant", "contraste"),
        ("rousseau", "constant", "crítica"),
        ("constant", "mill", "influencia"),
        ("constant", "berlin", "influencia"),
        ("mill", "berlin", "influencia"),
        ("kant", "berlin", "crítica"),
        ("kant", "rawls", "influencia"),
        ("mill", "hayek", "influencia"),
        ("berlin", "hayek", "afinidad"),
        ("maquiavelo", "skinner", "recuperación"),
        ("skinner", "pettit", "influencia"),
        ("berlin", "pettit", "crítica"),
        ("rawls", "sen", "crítica"),
        ("berlin", "sen", "crítica"),
        ("hobbes", "strauss", "interpretación"),
        ("maquiavelo", "strauss", "interpretación"),
        ("montesquieu", "rawls", "influencia"),
        ("rawls", "pettit", "diálogo"),
    ],
}
